# Site settings
title: "Chris's Blog"
email: your-email@example.com
description: >-
  My personal blog where I share thoughts and experiences 
  about technology, programming, and other interests.
baseurl: "" # Empty since this is a user/organization site
url: "https://chris1sflaggin.github.io" # Your GitHub Pages URL

# Social media
github_username: Chris1sFlaggin

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for GitHub Pages

# Additional settings
timezone: Europe/Rome
lang: en
author: Chris

# Exclude development-related files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - .git/
  - .gitignore
