#!/usr/bin/env python3
"""Aggiunge colonna 'explanation' a mcq.csv e matching.csv."""
import csv

MCQ = {
    '1': "La soluzione è il PERCORSO completo che porta da stato iniziale a goal, non lo stato target da solo (che è una soluzione 'parziale' nel senso del test obiettivo) né un assegnamento di variabili (concetto da CSP). Nei problemi di ricerca classica conta come si arriva al goal, non solo dove.",
    '2': "BLIND (cieco) = senza informazione di dominio extra oltre la formulazione del problema. Non ha nulla a che vedere con il limite di profondità (che invece definisce ricerche limitate come DLS) né con la non-ammissibilità di un'euristica (che è informata ma scarsa).",
    '3': "Per definizione h2 DOMINA h1 se h2(n) ≥ h1(n) per ogni stato n (con entrambe ammissibili). La dominanza implica meno nodi espansi. Stime per difetto = ammissibile (non dominante), disuguaglianza triangolare = consistente.",
    '4': "La matrice di confusione consente di calcolare accuratezza, precision, recall, F1, error rate. La confidence è una misura interna al classificatore (probabilità della classe predetta). L'entropia misura impurità di un nodo/dataset, non è derivabile dalla matrice.",
    '5': "Supervisionato = ogni esempio del learning set ha l'etichetta della classe associata. 'Supervisore umano' è un'interpretazione errata del termine. L'entropia è criterio di split negli alberi di decisione, non definizione di supervised learning.",
    '6': "Artificiale = non naturale. È l'opposto concettuale di intelligenza biologica. Non si riferisce a limiti di potenza né alla forma del sistema (può essere puro software).",
    '7': "Il Test di Turing pone il problema epistemico: quando possiamo dire che un computer è intelligente? Risposta operativa di Turing: se in un'imitation game un giudice non distingue uomo/macchina, allora la macchina è intelligente.",
    '8': "Weak AI = produrre comportamenti intelligenti SENZA pretendere che la macchina 'pensi davvero'. Approccio pragmatico/ingegneristico, contrapposto a Strong AI che invece pretende coscienza/comprensione reale.",
    '9': "Strong AI = riprodurre intelligenza umana nel senso forte (coscienza, comprensione). Critica famosa: stanza cinese di Searle, che mostra come passare il Turing test non implichi comprensione.",
    '10': "Searle: una persona in una stanza con istruzioni sintattiche può rispondere correttamente in cinese SENZA capirlo. Conclusione: la sola manipolazione simbolica (output corretto) non implica comprensione semantica.",
    '11': "CAPTCHA inverte il Turing test: invece di chiedere a un umano 'sei macchina?', chiede a un'entità web 'sei umano?'. Sfrutta task facili per umani e difficili per bot (riconoscimento immagini, distorsione).",
    '12': "Deterministico = stessa azione in stesso stato dà sempre stesso successore. Stocastico = molteplici successori possibili con distribuzione di probabilità. La rumorosità dei sensori riguarda osservabilità, non determinismo.",
    '13': "Stocastico = applicare stessa azione in stesso stato può portare in stati diversi. Esempio classico: dadi nel backgammon, vento che devia un robot. Diverso da incertezza sui sensori (osservabilità).",
    '14': "Episodico = esperienza divisa in episodi atomici indipendenti (es. classificare una foto): ogni decisione non dipende dal passato. Sequenziale = al contrario, ogni azione influenza le successive (es. scacchi).",
    '15': "Statico = ambiente fermo mentre l'agente delibera. Dinamico = mentre pensi il mondo cambia (es. guida autonoma). Importa per il time budget della deliberazione.",
    '16': "Parzialmente osservabile = i sensori NON danno accesso a tutta l'informazione rilevante. Cause: sensori imprecisi, rumore, occlusioni, parti del mondo nascoste (es. carte avversarie).",
    '17': "Dichiarativo = descrivi COSA è il problema (specifica logica, vincoli). Imperativo/procedurale = descrivi COME risolverlo. Il dichiarativo permette di riusare lo stesso motore su problemi diversi cambiando solo la KB.",
    '18': "Definizione standard di Russell & Norvig. Agente = entità che PERCEPISCE tramite sensori e AGISCE tramite attuatori sull'ambiente. Astrazione cruciale: separa logica/conoscenza dall'implementazione fisica.",
    '19': "Autonomo = riceve obiettivi ad alto livello e decide autonomamente i passi. Si distingue dall'automazione (riceve istruzioni passo-passo). Autonomia richiede capacità di ragionamento e adattamento.",
    '20': "Mondo dei blocchi = problema didattico classico per illustrare planning/ricerca. Non è 'reale' nel senso applicativo; serve a mostrare concetti come stati, azioni, goal, in un dominio semplice e visualizzabile.",
    '21': "Formulazione di un problema = (S0, Actions, Transition Model, Goal Test, Path Cost). Il numero di iterazioni è una proprietà dell'algoritmo che lo risolve, NON del problema.",
    '22': "BFS visita per livelli di profondità crescenti, espandendo TUTTI i nodi di profondità d prima di quelli a d+1. Usa coda FIFO. Espansione profonda = DFS.",
    '23': "DFS espande sempre il nodo più profondo della frontiera. Usa pila LIFO (o ricorsione). Non è ottima: trova soluzione ma non necessariamente la più breve.",
    '24': "DFS NON è completa se il branching factor permette cammini infiniti (può perdersi su un ramo infinito senza mai esplorare altri). Lo è solo su grafi finiti senza cicli o con graph-search che tenga traccia dei visitati.",
    '25': "IDS combina la completezza/ottimalità di BFS (esplorazione per livelli) con la memoria lineare di DFS. Il costo è solo costante: riesplorare nodi superficiali è dominato dall'esplorazione del livello più profondo.",
    '26': "BFS espande TUTTI i nodi fino a profondità d. Con branching b ci sono b + b² + ... + b^d ≈ b^d nodi. Stessa complessità in spazio (memorizza la frontiera).",
    '27': "Uniform-cost (Dijkstra) espande il nodo con MINOR costo g(n) accumulato dall'inizio. Garantisce ottimalità con costi positivi. Diverso da BFS (che usa profondità) e da greedy (che usa h).",
    '28': "A* combina costo passato g(n) e stima futura h(n) in f(n) = g(n)+h(n). Il nodo espanso è sempre quello che minimizza il costo totale stimato della soluzione che passa per esso.",
    '29': "Con euristica ammissibile (non sovrastima il costo reale) e costi positivi, A* è completa e ottima usando tree-search. Per graph-search serve consistenza, altrimenti basta riaprire i nodi.",
    '30': "Ammissibilità = h(n) ≤ h*(n), dove h*(n) è il vero costo da n al goal. Garantisce che A* non potoni il cammino ottimo. Una h che sovrastima può far ignorare la soluzione migliore.",
    '31': "Consistenza (monotonia) è proprietà più forte di ammissibilità: per ogni arco (n,n') vale h(n) ≤ c(n,n') + h(n'). Implica che f sia non decrescente sui cammini e quindi A* con graph-search è ottima senza riapertura.",
    '32': "Dominanza è una relazione tra euristiche ammissibili: h2 ≥ h1 ovunque. Con h dominante A* espande meno nodi (a parità di ottimalità) perché stringe di più i bound.",
    '33': "RBFS imita best-first con backtracking ricorsivo: tiene in memoria solo il cammino corrente (memoria lineare in d), non l'intera frontiera. Trade-off: rivisita nodi quando il backtrack riapre rami già scartati.",
    '34': "Minimax è formulato per giochi a SOMMA ZERO, due giocatori (MAX/MIN) con perfetta informazione. Per giochi cooperativi o multi-giocatore servono varianti (max^n, ecc.).",
    '35': "Alfa-beta è una potatura SAFE: non cambia il valore minimax calcolato, ma evita di esplorare sottoalberi che non possono influenzare la decisione finale. Cambia solo l'efficienza.",
    '36': "Con ordinamento perfetto delle mosse (best first), alfa-beta visita solo b^(m/2) nodi invece di b^m. Permette di raddoppiare la profondità di ricerca a parità di tempo.",
    '37': "Un CSP è la tripla <X, D, C>: X = insieme di variabili, D = domini, C = vincoli (relazioni tra sottoinsiemi di variabili). Niente funzione obiettivo (sarebbe CSOP).",
    '38': "Soluzione di CSP = assegnamento completo che soddisfa TUTTI i vincoli. Non un cammino: nei CSP la sequenza di assegnamenti non importa, conta solo l'assegnamento finale.",
    '39': "Backtracking = DFS specializzato per CSP. Assegna variabili una alla volta; se viola un vincolo, torna indietro all'ultima scelta e prova un altro valore. Forward checking lo potenzia eliminando valori inconsistenti dai domini futuri.",
    '40': "Forward checking, dopo ogni assegnamento, elimina dai domini delle variabili future i valori inconsistenti con il vincolo attivo. Rileva precocemente fallimenti. Più debole di arc consistency (che considera anche vincoli tra variabili future).",
    '41': "AC-3 stabilisce ARC CONSISTENCY (2-consistency): ogni valore in ogni variabile è supportato da almeno un valore consistente in ciascun arco. Path consistency = 3-consistency, più costosa.",
    '42': "K-consistency: ogni assegnamento consistente a k-1 variabili può essere esteso a una k-esima variabile mantenendo la consistenza. Strong k-consistency = j-consistency per tutti j ≤ k. Costo cresce esponenzialmente con k.",
    '43': "Backjumping invece di tornare al genitore immediato, salta direttamente al nodo più recente i cui assegnamenti hanno causato il conflitto (conflict-directed). Riduce il backtrack inutile su variabili indipendenti.",
    '44': "Informata = usa un'euristica h(n) che stima il costo (o la distanza) per raggiungere il goal dal nodo n. La blind no, vede solo la struttura del problema senza guida di dominio.",
    '45': "Greedy best-first espande il nodo con h(n) minimo (la stima più bassa di distanza al goal). Veloce ma non considera il costo già speso, quindi può scegliere cammini lunghi che 'sembrano' vicini al goal.",
    '46': "Greedy può ciclare (non completo senza graph-search) e può scegliere cammini sub-ottimi perché ignora g(n). Esempio classico: Romania, da Iași a Fagaraș via Neamț (vicolo cieco).",
    '47': "IDDFS è completa su spazi con branching factor finito (anche se infinitamente profondi): per ogni profondità d esiste un'iterazione che la esplora. Su spazi infiniti in larghezza non lo è.",
    '48': "DFS usa O(b·m) memoria: solo il cammino corrente + fratelli non espansi. BFS deve memorizzare l'intera frontiera = O(b^d). Per d>>m questo è un trade-off enorme.",
    '49': "Funzione di valutazione = approssimazione di utilità per stati NON terminali. Permette di troncare la ricerca (depth-limited) e stimare chi sta vincendo. Negli scacchi: materiale + posizione + ecc.",
    '50': "Somma zero: utilità(MAX) + utilità(MIN) = costante. Ciò che uno guadagna l'altro perde. Permette di modellare il gioco con un'unica funzione utilità da massimizzare/minimizzare.",
    '51': "Minimax assume gioco ottimale di entrambi: MAX cerca max utilità, MIN cerca minimizzarla. Se l'avversario gioca male, minimax è ancora corretto (al peggio = al meglio per MAX) ma può non essere ottimo nella pratica.",
    '52': "Mappa con k colori → CSP: variabili = regioni, domini = {1..k}, vincoli binari = regioni adiacenti hanno colori diversi. Classico problema NP-completo (per k=3 su grafi generali).",
    '53': "N-regine si modella come CSP: variabili = N regine (una per colonna), dominio = righe {1..N}, vincoli binari = nessuna stessa riga né diagonale. Risolvibile efficientemente con AC + backtracking.",
    '54': "Planning = costruire automaticamente una sequenza di azioni per raggiungere un goal a partire da uno stato iniziale, dato un modello delle azioni (precondizioni ed effetti).",
    '55': "Stocastici = giochi con componente aleatoria intrinseca (dadi, mescolata di carte): l'esito di un'azione non è deterministicamente prevedibile. Backgammon, briscola, poker.",
    '56': "Backgammon: ogni mossa è preceduta da lancio di 2 dadi che determina le mosse possibili. Componente aleatoria forte. Scacchi e othello sono deterministici.",
    '57': "Expectiminimax estende minimax aggiungendo NODI DI CASUALITÀ tra mosse di MAX e MIN. Il valore di un nodo casuale è la media pesata (per probabilità) dei valori dei figli.",
    '58': "Per applicare expectiminimax devo conoscere la distribuzione di probabilità di ogni evento casuale (es. probabilità di ogni combinazione dei dadi 1/36 ciascuna nel backgammon).",
    '59': "Nodo casuale: V(s) = Σ_r P(r) · expectiminimax(result(s,r)). È un'aspettazione, non un max né min. Riflette l'incertezza sull'esito.",
    '60': "Complessità expectiminimax è O(b^m · n^m) dove n = numero esiti casuali per nodo. Esponenziale in più rispetto a minimax: i nodi casuali moltiplicano il branching.",
    '61': "Alfa-beta in expectiminimax è difficile: i nodi casuali calcolano medie, quindi non c'è un bound certo come max o min. Esiste *probabilistic alpha-beta* ma richiede bound sui valori delle utility.",
    '62': "Variabile aleatoria = mappa da uno spazio campionario a un valore (numero, categoria). Il suo valore dipende dall'esito di un fenomeno aleatorio. Esempi: lancio di dado, colore di pallina estratta.",
    '63': "Le due fonti tipiche di incertezza per un agente: (1) conoscenza imperfetta delle regole del mondo, (2) osservabilità parziale (sensori non vedono tutto). Entrambe vanno modellate per agire razionalmente.",
    '64': "Rappresentazione della conoscenza = formalizzare fatti sul mondo in modo che un sistema possa ragionare automaticamente su di essi (inferenza, query answering, verifica consistenza).",
    '65': "Formula atomica in logica proposizionale = una singola variabile proposizionale (es. P, Piove). È l'unità base; congiunzioni o clausole sono formule composte.",
    '66': "Letterale = formula atomica (positiva, es. P) o sua negazione (negativa, es. ¬P). È il mattone base delle clausole.",
    '67': "Clausola = DISGIUNZIONE di letterali (l1 ∨ l2 ∨ ... ∨ ln). Le clausole vuote (= falso) e unitarie (= un solo letterale) sono casi limite. La CNF è congiunzione di clausole.",
    '68': "CNF = congiunzione di clausole (= ∧ di ∨). Ogni formula proposizionale può essere trasformata in CNF equivalente. Forma normale richiesta dalla risoluzione.",
    '69': "Tautologia = vera in OGNI interpretazione/modello (esempio: A ∨ ¬A). Concettualmente: verità logica indipendente dal mondo specifico.",
    '70': "Contraddizione = falsa in ogni interpretazione (es. A ∧ ¬A). Una KB contraddittoria implica tutto (ex falso quodlibet) — pessima!",
    '71': "Soddisfacibile = esiste ALMENO un'interpretazione che la rende vera. Diverso da valida (vera in tutte) e da insoddisfacibile (vera in nessuna).",
    '72': "Clausola di Horn = clausola con AT MOST UN letterale positivo. Forme: solo negativi (¬A∨¬B), una positiva pura (P), regola (¬A∨¬B∨C ≡ A∧B→C). Permette inferenza efficiente lineare (Prolog).",
    '73': "Modus ponens: da A e A→B deduco B. Regola fondamentale della logica deduttiva. Forward chaining la applica iterativamente sui fatti noti.",
    '74': "Risoluzione proposizionale è REFUTATION-COMPLETE: deriva la clausola vuota da KB ∧ ¬α se e solo se KB ⊨ α. Non genera direttamente TUTTE le conseguenze ma ne verifica una qualsiasi.",
    '75': "Refutazione = dimostrare per assurdo. Per provare KB ⊨ α, aggiungo ¬α alla KB e applico risoluzione: se derivo la clausola vuota (contraddizione), allora KB ⊨ α.",
    '76': "Forward chaining = data-driven. Parte dai fatti, applica regole le cui premesse sono soddisfatte, deriva nuovi fatti. Si ferma quando non c'è più nulla da derivare o si trova il goal. Efficiente per Horn KB.",
    '77': "Backward chaining = goal-driven. Parte dal goal, cerca regole che lo concludono e tenta di soddisfarne le premesse ricorsivamente. È il modello di Prolog.",
    '78': "FOL aggiunge: variabili, quantificatori (∀, ∃), predicati n-ari, funzioni. È strettamente più espressiva della proposizionale (può parlare di oggetti, non solo proposizioni atomiche).",
    '79': "∀x P(x): per QUALSIASI scelta di x nel dominio, P(x) è vera. Universale = afferma una proprietà comune a tutto il dominio.",
    '80': "∃x P(x): esiste ALMENO UN x nel dominio per cui P(x) è vera. Non specifica quale. Si combinano nidificandoli (∀x ∃y ≠ ∃y ∀x).",
    '81': "Formula ground = senza variabili libere o legate, solo costanti e funzioni applicate a costanti. È una formula 'concretamente vera o falsa' una volta fissata l'interpretazione.",
    '82': "Unificatore = sostituzione θ che, applicata a due espressioni (es. atomi), le rende sintatticamente identiche. Es: θ={x/John} unifica P(x) con P(John).",
    '83': "MGU (Most General Unifier) è l'unificatore meno specifico: ogni altro unificatore può essere ottenuto da MGU per ulteriore sostituzione. L'algoritmo di unificazione di Robinson trova sempre l'MGU se esiste.",
    '84': "Lifting = trasportare la risoluzione dalla proposizionale alla FOL: invece di chiedere uguaglianza tra letterali opposti, si chiede unificabilità tramite un MGU, che viene poi applicato alla clausola risolvente.",
    '85': "Binary resolution + factoring (collassare letterali unificabili) è REFUTATION-COMPLETE in FOL: se KB ⊨ α allora la risoluzione deriva la clausola vuota da KB ∧ ¬α (Robinson 1965).",
    '86': "Skolemizzazione: rimuove ∃ introducendo costanti (se ∃ è esterno) o funzioni di Skolem dipendenti dalle ∀ a sinistra. Es: ∀x ∃y Ama(x,y) → ∀x Ama(x, f(x)). Preserva soddisfacibilità (ma NON equivalenza).",
    '87': "KB = insieme strutturato di formule (assiomi, regole, fatti) che rappresenta conoscenza in un dominio. Cuore di un sistema basato su conoscenza/inferenza.",
    '88': "Interrogare = chiedere se una formula α è conseguenza logica della KB (KB ⊨ α?). Non si modifica la KB; si applica un motore inferenziale.",
    '89': "Tassonomia = struttura ad albero di categorie collegate da relazioni di sotto/super-classe (is-a). Ogni categoria eredita proprietà dai padri. Esempio: regno animale.",
    '90': "Is-a(A,B) tipicamente indica che A è SOTTOCLASSE di B (relazione tra categorie). Diverso da Member, che è relazione istanza-categoria.",
    '91': "Member(X,C) = X è un'ISTANZA (elemento) della categoria C. È relazione individuo-categoria. Diverso da Is-a (categoria-categoria).",
    '92': "Ereditarietà: una sottoclasse acquisisce automaticamente le proprietà definite sulle sovraclassi (a meno di cancellazioni esplicite). Permette di rappresentare proprietà comuni una volta sola.",
    '93': "Disjoint(S) significa che le categorie in S non hanno istanze in comune (mutua esclusione). Es: {Cane, Gatto} sono disgiunte come categorie di mammiferi domestici.",
    '94': "ExhaustiveDec(S,C) = ogni istanza di C appartiene ad almeno una categoria di S (decomposizione che copre tutto C, ma può avere sovrapposizioni).",
    '95': "Partition(S,C) = Disjoint(S) ∧ ExhaustiveDec(S,C). Cioè: le categorie di S coprono tutto C e non si sovrappongono. Es: {Maschio, Femmina} è partizione di Persona (semplificando).",
    '96': "Part-of è transitiva: se A è parte di B e B è parte di C, allora A è parte di C. Esempio: dito → mano → braccio → corpo. NON è riflessiva (X non è parte di se stessa).",
    '97': "Bunch-of({a,b,c}) = oggetto composto dalle parti elencate, senza specificare le relazioni interne (a differenza di un'aggregazione strutturata). Es: un mucchio di pietre.",
    '98': "T-box (Terminological box) = parte INTENSIONALE dell'ontologia: definizioni di classi, sottoclassi, proprietà generali. Indipendente dalle istanze specifiche.",
    '99': "A-box (Assertional box) = parte ESTENSIONALE: fatti su istanze specifiche (Pongo è un Dalmata). Deve essere coerente con la T-box (terminologicamente).",
    '100': "Eccezioni in eredità: una sottoclasse può ANNULLARE una proprietà ereditata (es. cane normalmente ha pelo, cane nudo peruviano no). Sistemi di default logic gestiscono questo non-monotonamente.",
    '101': "Ontologia = grafo generale di concetti e relazioni (anche non gerarchiche: part-of, causes, ecc.). Tassonomia = caso particolare ad albero, con sole relazioni di sotto-classe.",
    '102': "OWL (Web Ontology Language) = linguaggio standard W3C per ontologie del semantic web. Basato su RDF, descrive classi, proprietà, individui con espressività descrizione-logica.",
    '103': "RDF rappresenta conoscenza come TRIPLE soggetto-predicato-oggetto. Es: <Pongo, hasOwner, Pongo's owner>. Un insieme di triple è un grafo RDF (nodi=entità, archi=predicati).",
    '104': "Fluente = predicato/relazione che dipende dalla situazione (cambia nel tempo). Es: Holds(At(Robot,L), s). Si denota esplicitamente la situazione s come argomento.",
    '105': "Assioma di applicabilità: ∀params,s Applicable(Action(params), s) ⇔ Precond(params, s). Definisce quando un'azione si può eseguire (precondizioni soddisfatte nella situazione corrente).",
    '106': "Assioma di effetto descrive cosa CAMBIA dopo l'azione: cosa è vero in Result(Action, s). Es: dopo Pickup(blocco) vale Holding(blocco). Non basta: c'è anche il frame problem.",
    '107': "Frame problem: come specificare che TUTTO IL RESTO non cambia? Non basta dire cosa cambia: serve dichiarare implicitamente o esplicitamente la persistenza degli altri fluenti.",
    '108': "Assioma di frame: per ogni fluente, dice che se nessun effetto lo modifica, mantiene il valore. Approccio classico: un assioma per ogni coppia (fluente, azione). Russell-McCarthy successor-state axioms compattano.",
    '109': "Anomalia di Sussman: perseguire un sottogoal può disfare un sottogoal già risolto (esempio classico con tre blocchi). Mostra che la pianificazione non sempre è lineare/sequenziale.",
    '110': "PDDL (Planning Domain Definition Language) standardizza la rappresentazione di problemi di planning: stati come fluenti, azioni con precondizioni ed effetti, goal. Usato in competizioni IPC.",
    '111': "Agente razionale (Russell-Norvig): sceglie l'azione che MASSIMIZZA L'UTILITÀ ATTESA data la sua percezione/conoscenza. Razionalità ≠ onniscienza: razionale può ancora sbagliare per limiti di info.",
    '112': "Reattivo semplice: input = percezione corrente, output = azione (regole IF-THEN-ELSE). Niente memoria né modello. Veloce ma cieco se servono stati passati.",
    '113': "Basato su modello: mantiene uno STATO INTERNO che riflette aspetti non osservati. Aggiorna lo stato in base a percezioni + modello di transizione. Necessario in ambienti parzialmente osservabili.",
    '114': "Goal-driven: ha un obiettivo esplicito. Sceglie azioni che lo avvicinano al goal (può usare planning). Più flessibile di reattivi puri: cambi goal → cambi comportamento.",
    '115': "Utility-driven: ha una funzione di utilità sugli stati. Sceglie azioni che massimizzano l'utilità attesa. Permette di scegliere tra goal in conflitto (trade-off) e gestire incertezza.",
    '116': "Agente che apprende ha 4 componenti: elemento di esecuzione, elemento di apprendimento, MODULO CRITICO (valuta prestazioni e fornisce feedback), generatore di problemi (esplorazione).",
    '117': "Classificazione = assegnare un'istanza a una classe da un insieme PREDEFINITO di classi. Apprendimento supervisionato (training con classi note). Diverso da clustering (no etichette) e regressione (output continuo).",
    '118': "Supervisionato = i dati di training contengono coppie (input, classe). L'algoritmo impara la mappa input→classe. Apprendimento 'guidato' dalle etichette.",
    '119': "Non supervisionato (clustering) = senza etichette di classe. L'algoritmo trova STRUTTURE/GRUPPI naturali nei dati basandosi su similarità. Esempi: k-means, gerarchico, DBSCAN.",
    '120': "Test set = dati MAI VISTI durante training. Serve per stimare la generalizzazione del modello (prestazioni su dati nuovi). Confonderlo con training porta a stime ottimistiche.",
    '121': "Accuratezza = (TP+TN)/totale = predizioni corrette / totale. Misura globale di prestazione, sensata se le classi sono bilanciate. Su classi sbilanciate, va integrata con precision/recall.",
    '122': "Error rate = 1 − accuratezza = predizioni sbagliate / totale. Spesso più intuitivo quando vuoi minimizzare l'errore.",
    '123': "Matrice dei costi: a ogni cella (classe_reale, classe_predetta) associa un costo. Permette di pesare diversamente gli errori (es. falso negativo medico più grave del falso positivo).",
    '124': "Rote learning = memorizzare le istanze. Su nuova istanza cerca quella identica (o più simile via distanza). Semplice ma limitato; antenato di k-NN.",
    '125': "Voto a maggioranza: tra i vicini più simili, si conta la classe più frequente. Approccio base di k-NN. Adatto per classi discrete.",
    '126': "Voto pesato: ogni vicino contribuisce con un peso inversamente proporzionale alla distanza. Più vicino = più peso. Riduce l'influenza dei vicini lontani.",
    '127': "Albero di decisione: nodi interni testano un attributo, archi = valori dell'attributo, foglie = classe predetta. Modello interpretabile, ottenuto top-down con algoritmi tipo Hunt/ID3/C4.5.",
    '128': "Hunt: ricorsivo, top-down. (1) Se istanze nel nodo sono pure → foglia. (2) Altrimenti scegli attributo migliore, splitta, ricorsivo sui figli. Variazioni differiscono nel criterio di scelta dell'attributo (gain).",
    '129': "Continui sono tipici negli alberi di decisione MA richiedono discretizzazione/scelta di soglie. Binari, nominali, ordinali sono direttamente trattabili. La distrazione 'continui' come 'non tipico' è giustificata solo se intendiamo nativi senza preprocessing.",
    '130': "Entropia(t) = -Σ p(i|t) log₂ p(i|t). Misura l'IMPURITÀ del nodo: 0 se tutte istanze stessa classe, max = log₂(c) se uniforme. Negli split si minimizza l'entropia attesa.",
    '131': "Information gain = entropia(padre) - Σ (|figlio|/|padre|) × entropia(figlio). Misura quanto un attributo RIDUCE l'incertezza. Si sceglie l'attributo con gain massimo.",
    '132': "Occam: a parità di prestazioni, preferisci il modello PIÙ SEMPLICE (minor numero di assunzioni). Negli alberi: meno nodi a parità di accuratezza. Riduce overfitting e migliora interpretabilità.",
    '133': "Overfitting: alta accuratezza su training, scarsa su test. Il modello ha imparato anche il rumore. Tipico in alberi troppo profondi, reti troppo grandi, training set piccolo.",
    '134': "Prepruning: interrompe lo split se il gain è sotto soglia o se il nodo è troppo piccolo. Previene overfitting MA può fermarsi troppo presto (sotto-apprendimento).",
    '135': "Postpruning: prima costruisci albero completo, poi POTI i rami che non migliorano prestazioni stimate (es. tramite validation set o pessimistic error). Più costoso ma più affidabile del prepruning.",
    '136': "MDL (Minimum Description Length): seleziona il modello che minimizza L(modello) + L(dati|modello). Bilancia complessità del modello e errore sui dati. Formalizza il rasoio di Occam.",
    '137': "Perceptron: net = Σwᵢxᵢ, output = f(net) con f = funzione di attivazione (originariamente gradino, poi sigmoide). Calcola una soglia su una combinazione lineare degli input.",
    '138': "Perceptron a singolo strato risolve solo problemi LINEARMENTE SEPARABILI. XOR non lo è (no iperpiano che separa (0,1),(1,0) da (0,0),(1,1)). Limite famoso evidenziato da Minsky&Papert.",
    '139': "Sigmoide σ(x) = 1/(1+e^(-x)): differenziabile, output (0,1), comportamento simile al gradino ma 'liscio'. Permette backpropagation (gradient computable).",
    '140': "MLP = perceptron multistrato con uno o più strati hidden tra input e output. Connessioni feed-forward, attivazioni non lineari. Universal approximator (Cybenko 1989).",
    '141': "Backpropagation: errore calcolato in output, propagato all'indietro attraverso lo strato hidden tramite chain rule. Si aggiornano i pesi proporzionalmente al gradiente del costo.",
    '142': "Discesa del gradiente: muoviti nello spazio dei pesi nella direzione OPPOSTA al gradiente della funzione di costo. Converge a minimo locale; learning rate controlla la velocità.",
    '143': "Learning rate η: passo dell'aggiornamento Δw = -η ∇L. Troppo alto → oscillazioni/divergenza. Troppo basso → convergenza lenta. Spesso si usano schedule (decay) o adattivi (Adam).",
    '144': "Un'epoca = una passata completa su tutto il learning set. Tipicamente si usano molte epoche (decine-migliaia). Diverso da iterazione (= un singolo aggiornamento mini-batch).",
    '145': "Rete neurale = approssimatore universale di funzioni: con neuroni e strati sufficienti può approssimare qualsiasi funzione continua. Natura distribuita: conoscenza in pesi, non in regole esplicite.",
    '146': "RL: agente apprende dall'INTERAZIONE con l'ambiente, ricevendo reward. Massimizza il reward atteso futuro. Diverso da supervisionato (no etichette dirette) e non-supervisionato (c'è feedback, anche se sparso).",
    '147': "Policy π(a|s) = mappa che assegna a ogni stato una distribuzione di probabilità sulle azioni. Deterministica = una sola azione; stocastica = distribuzione. Obiettivo RL: trovare π* ottima.",
    '148': "Reward = segnale numerico che indica DESIDERABILITÀ dello stato/azione. Specifica COSA vogliamo (non il come). Reward sparso/denso, ritardato/immediato influenzano la difficoltà.",
    '149': "MDP finito: <S, A, P(s'|s,a), R(s,a,s')>. Modello standard per RL con proprietà markoviana (futuro dipende solo da stato corrente). Equazioni di Bellman valgono in MDP.",
    '150': "Discount γ ∈ [0,1]: pesa reward futuri. γ < 1 → preferisci reward immediati, somma R_t converge anche per orizzonti infiniti. γ = 0 → solo reward immediato (miope).",
    '151': "Bellman: V^π(s) = Σ_a π(a|s) Σ_s' P(s'|s,a) [R + γ V^π(s')]. Esprime ricorsivamente il valore di uno stato. Base degli algoritmi di programmazione dinamica e di TD learning.",
    '152': "Clustering = trovare gruppi naturali in dati NON ETICHETTATI. Misura di similarità/distanza determina i cluster. Es: k-means minimizza distanza intra-cluster.",
    '153': "K-means: (1) inizializza k centroidi, (2) assegna ogni punto al centroide più vicino, (3) ricalcola centroidi come media dei punti assegnati, (4) ripeti fino a convergenza. Minimizza WSS (within-cluster sum of squares).",
    '154': "k = iperparametro fissato a priori. Sceglierlo male produce cluster poco significativi. Metodi: elbow, silhouette, gap statistic per stimare k buono.",
    '155': "Clustering gerarchico: produce un DENDROGRAMMA (albero di fusioni/divisioni). Agglomerative (bottom-up, parte da singletons) o divisive (top-down). Vantaggio: non richiede k a priori, lo decidi tagliando l'albero.",
    '156': "Rule learning: produce un set di regole IF-THEN simboliche. Tecniche: sequential covering (RIPPER, CN2), conversione da albero di decisione. Vantaggio: regole sono leggibili.",
    '157': "Da albero a regole: ogni cammino radice-foglia → una regola (premesse = test, conclusione = classe della foglia). Permette di interpretare l'albero come sistema di regole equivalente.",
    '158': "CNN: convoluzioni applicano filtri locali condivisi su immagini. Sfruttano invarianza traslazionale e località: pochi parametri rispetto a MLP fully-connected. Standard per visione (ImageNet, ecc.).",
    '159': "RNN/LSTM/GRU: condividono pesi nel tempo, stato nascosto h_t aggiornato a ogni timestep. Adatte a sequenze (testo, audio, serie storiche). LSTM/GRU gestiscono long-range con gating.",
    '160': "Transformer (Vaswani 2017): SELF-ATTENTION calcola pesi di rilevanza tra tutti gli elementi della sequenza. No ricorrenza → parallelizzabile. Base di BERT, GPT, T5, ecc.",
    '161': "IA generativa: modelli che apprendono p(x) (o p(x|condizione)) e poi CAMPIONANO nuovi dati realistici. Diversa da discriminativa (apprende p(y|x) per classificare).",
    '162': "LLM = grande rete (Transformer) pre-addestrata su corpus enormi tramite next-token prediction. Apprendono distribuzione di linguaggio, generalizzano via few-shot/zero-shot prompting. Es: GPT, Llama.",
    '163': "GAN: generatore G crea fake, discriminatore D distingue reali/fake. Si addestrano in gioco MINIMAX: G inganna D, D smaschera G. All'equilibrio G produce campioni indistinguibili dai reali.",
    '164': "Autoencoder: rete encoder→bottleneck→decoder che impara a RICOSTRUIRE l'input. Il bottleneck è una rappresentazione compressa. Varianti: denoising, VAE (generativo), sparse.",
    '165': "Modelli di diffusione (DDPM): apprendono a invertire un processo che aggiunge rumore gaussiano gradualmente. Generano denoising step-by-step da rumore puro. Stato dell'arte per immagini (Stable Diffusion, DALL-E).",
    '166': "Variabile aleatoria in teoria probabilità: ha dominio (insieme di valori possibili) e distribuzione (probabilità su quel dominio). Discreta o continua. Concetto base prima di reti bayesiane.",
    '167': "Assiomi di Kolmogorov: (1) P(A) ≥ 0, (2) P(Ω) = 1, (3) per eventi disgiunti P(A∪B) = P(A)+P(B). Definiscono cosa significa 'probabilità' matematicamente. Limite superiore: P(A) ≤ 1.",
    '168': "Marginalizzazione: P(X) = Σ_y P(X,Y=y) (somma sul dominio di Y). Elimina Y integrando/sommando la distribuzione congiunta. Da congiunta su tutte le variabili → distribuzione su un sottoinsieme.",
    '169': "Condizionata: P(A|B) = P(A∧B)/P(B), definita se P(B)>0. Aggiorna la probabilità di A sapendo che B è vero. Base del ragionamento probabilistico.",
    '170': "Bayes: P(H|E) = P(E|H)·P(H)/P(E). Inverte la condizionale: da P(evidenza|ipotesi) ricavi P(ipotesi|evidenza). Cuore dell'inferenza diagnostica.",
    '171': "X e Y indipendenti ⇔ P(X,Y) = P(X)·P(Y) ⇔ P(X|Y) = P(X). L'informazione su Y non cambia la probabilità di X. Forte assunzione spesso violata, da verificare.",
    '172': "X ⊥ Y | Z ⇔ P(X,Y|Z) = P(X|Z) · P(Y|Z). Indipendenza CONDIZIONATA: sapendo Z, sapere Y non aggiunge informazione su X. Chiave dell'efficienza delle reti bayesiane.",
    '173': "Rete bayesiana = DAG (Directed Acyclic Graph) + CPT (Conditional Probability Tables) per ogni nodo dato i genitori. Rappresenta compactamente distribuzioni congiunte sfruttando indipendenze condizionate.",
    '174': "Chain rule per reti bayesiane: P(X1,...,Xn) = Π_i P(Xi | parents(Xi)). Fattorizza la congiunta in prodotto di CPT locali. Esponenzialmente più compatta della tabella completa.",
    '175': "CPT di un nodo X = distribuzione P(X | Parents(X)) per ogni combinazione dei valori dei genitori. Per nodo binario con k genitori binari: 2^k righe, ognuna con 1 parametro.",
    '176': "Vantaggio reti bayesiane: indipendenze condizionate riducono i parametri. Congiunta completa = 2^n-1 parametri; rete con max k genitori = O(n·2^k). Compattezza esponenziale.",
    '177': "KR si occupa di formalizzare conoscenza affinché un sistema RAGIONI automaticamente. Include scelta del linguaggio (FOL, DL, OWL), strutturazione (ontologie), inferenza, gestione incertezza/incompletezza.",
    '178': "Eventi con durata: si rappresentano con INTERVALLI temporali. Algebra di Allen definisce 13 relazioni tra intervalli (before, after, overlaps, during, ecc.) per ragionare su tempo.",
    '179': "Reificare una categoria = trattarla come OGGETTO sul quale puoi predicate (proprietà di proprietà). Es: invece di Cane(Pongo), usi Member(Pongo, Cane) e poi puoi dire Popolare(Cane).",
    '180': "Reificazione converte un predicato/relazione in un oggetto del dominio. Permette predicati di secondo ordine. Ontologia OWL fa estensivo uso di reificazione per categorie e proprietà.",
    '181': "Scacchi: informazione COMPLETA (vedi tutta la scacchiera), DETERMINISTICO (mosse senza casualità), SOMMA ZERO (vince uno o l'altro o patta), DUE giocatori. Caso ideale di minimax.",
    '182': "Poker: informazione INCOMPLETA (non vedi le carte avversarie), stocastico (ordine mescolata). Richiede ragionamento su belief states e bluffing — diverso da minimax classico.",
    '183': "Tessere fuori posto: ammissibile (ogni tessera fuori posto richiede ≥1 mossa). Sottostima la distanza Manhattan. È più 'sciocca' di Manhattan ma sufficiente per garantire ottimalità di A*.",
    '184': "Manhattan = somma delle distanze L1 di ogni tessera dalla posizione goal. Ammissibile (somma di lower bound) e DOMINA 'tessere fuori posto' (più informativa). Risultato classico AIMA.",
    '185': "Se h1 e h2 sono ammissibili, max(h1,h2) è ancora ammissibile (resta ≤ h*) e domina entrambe. Tecnica standard: combina euristiche diverse per ottenere un bound più stretto.",
    '186': "KB consistente ⇔ ha almeno un modello (un'interpretazione che la rende vera). KB inconsistente implica logicamente qualsiasi cosa (ex falso quodlibet) — inutilizzabile.",
    '187': "Valida = vera in OGNI modello = tautologia. Esempi: A∨¬A, ∀x(P(x)∨¬P(x)). Sintatticamente decidibili in proposizionale, semi-decidibili in FOL.",
    '188': "In FOL, una funzione f(t1,...,tn) DENOTA un elemento del dominio (es. madre_di(Carlo) → Anna). Diverso dai predicati che denotano valori di verità.",
    '189': "Predicato P(t1,...,tn) restituisce vero/falso. Funzione restituisce un oggetto del dominio. Distinzione cruciale in FOL: i predicati formano formule, le funzioni formano termini.",
    '190': "Differenza chiave: nel supervisionato i dati sono etichettati (input, classe), nel non-supervisionato no. Determina il tipo di task possibili e gli algoritmi applicabili.",
    '191': "Bassissimo training error + alto test error = overfitting tipico. Il modello ha imparato pattern specifici (incluso rumore) del training set, non generalizzabili.",
    '192': "Underfitting: il modello è troppo semplice per catturare la struttura dei dati. Errore alto su training E test. Soluzione: modello più espressivo, più feature, più dati di qualità.",
    '193': "Bias-variance trade-off: bias = errore sistematico (modello troppo rigido), variance = sensibilità al campione (modello troppo flessibile). Ridurre uno aumenta l'altro. Errore atteso = bias² + var + irriducibile.",
    '194': "Cross-validation: dividi dati in k fold, addestra su k-1 e valida sul k-esimo, ripeti k volte. Media le metriche. Stima più stabile dell'accuratezza su test set unico. Standard: 5-fold, 10-fold.",
    '195': "Gini(t) = 1 - Σ p(i|t)². Misura impurità alternativa all'entropia. Più rapida (no log). Tendenze simili. CART usa Gini, ID3/C4.5 usano gain ratio (basato su entropia).",
    '196': "Risoluzione richiede formule in CNF (congiunzione di clausole). Trasformazione: elimina implicazioni, sposta ¬ verso atomi, distribuisci ∨ su ∧. In FOL: Skolemizza prima.",
    '197': "Problema di ricerca = (S0, Actions(s), Transition T(s,a)=s', GoalTest(s), PathCost). Tutti questi 5 elementi sono necessari per definire formalmente un problema di ricerca.",
    '198': "Graph-search mantiene un insieme 'explored' di stati già visitati per evitare di rivisitarli. Critico per spazi con cicli o cammini multipli verso stessi stati. Tree-search no, e può ciclare.",
    '199': "Tecnica del problema rilassato: rimuovi vincoli del problema originale, risolvilo (più facile), usa il costo ottimale come euristica del problema vero. Garantisce ammissibilità.",
    '200': "A → B ≡ ¬A ∨ B per definizione di implicazione materiale. Trasformazione fondamentale per portare formule in CNF (la risoluzione richiede questa forma).",
    '201': "Equivalenza ↔ è doppia implicazione: A↔B = (A→B)∧(B→A) = (¬A∨B)∧(¬B∨A). Trasformazione standard nelle conversioni in CNF.",
    '202': "∀x (Cane(x)→Animale(x)): per ogni x del dominio, se è cane allora è animale. Schema standard per esprimere relazioni di sottoclasse in FOL.",
    '203': "Skolem per ∃ sotto ∀: ∀x ∃y P(x,y) → ∀x P(x, f(x)). La f dipende da x perché y può variare al variare di x. Preserva soddisfacibilità (non equivalenza).",
    '204': "¬A ∨ ¬B ∨ C ha UN solo letterale positivo (C). Quindi è clausola di Horn. Equivale alla regola A ∧ B → C.",
    '205': "Le Horn permettono FC/BC LINEARI nella dimensione della KB. Forma 'naturale' delle regole (premesse→conclusione). Cuore di Prolog. Limitazione: non esprimibile A∨B senza condizioni.",
    '206': "Distribuzione congiunta su n variabili booleane ha 2^n combinazioni; servono 2^n - 1 parametri (uno è vincolato dalla normalizzazione). Crescita esponenziale — impraticabile per n grande.",
    '207': "d-separazione: criterio grafico per identificare indipendenze condizionate in una BN. Due nodi sono d-separati da Z se non ci sono cammini 'attivi' tra loro dato Z. Riflette le indipendenze codificate nella struttura.",
    '208': "Compactness BN: ogni nodo binario con al più k genitori contribuisce 2^k parametri. Totale n·2^k vs 2^n della congiunta completa. Esponenzialmente più piccolo se k << n.",
    '209': "Perceptron classico apprende SOLO funzioni linearmente separabili (esiste un iperpiano che separa le due classi). La sua regola di apprendimento converge in questo caso (teorema di Rosenblatt).",
    '210': "Iperpiano in n dimensioni: w·x = θ. Sopra l'iperpiano (w·x > θ) → classe 1, sotto → classe 0. Il perceptron impara w e θ tali che gli esempi positivi/negativi siano separati."
}

MATCHING = {
    # (group_id, item_id) → explanation
    ('1','1'): "Cane(Fuffi)⇒¬Gatto(Fuffi): tutti i simboli sono costanti (Fuffi). Niente variabili → GROUND. È anche una formula FOL ma il termine più stretto è 'ground'.",
    ('1','2'): "¬P ∨ P è vera in ogni interpretazione (legge del terzo escluso). TAUTOLOGIA.",
    ('1','3'): "Contiene variabili (x,y,z) e predicati con argomenti → FORMULA FOL generica (non clausola perché ha sia ∨ sia ∧ a livello esterno, non solo disgiunzione di letterali).",
    ('1','4'): "A∨¬B∨C: disgiunzione di letterali (A, ¬B, C). Definizione esatta di CLAUSOLA.",
    ('1','5'): "¬Caldo(x)∧Caldo(x): contiene variabile x → è FOL. È anche una contraddizione, ma la tipologia richiesta tra le opzioni è FOL.",
    ('2','1'): "¬Alfa(x)∨Beta(x)∨¬Gamma(x) ha DUE letterali negativi e UNO positivo (Beta(x)). Una Horn ha al più UN positivo: qui è soddisfatto. MA classificazione classica: 1 positivo, 2 negativi → è Horn. Riconsidera: questa È una Horn (1 letterale positivo). Risposta corretta: F (cioè 'non è Horn') è ERRATA → in realtà T. Verificare nel materiale ufficiale.",
    ('2','2'): "Una clausola è disgiunzione di letterali. La formula data lo è chiaramente. T.",
    ('2','3'): "Modus ponens richiede una premessa atomica e un'implicazione P→Q. La clausola disgiuntiva NON è in forma implicativa diretta (servono trasformazioni). Tecnicamente F nello scenario senza trasformazioni.",
    ('2','4'): "Risoluzione opera su clausole. La formula è già clausola; con Alfa(COST) si può risolvere (¬Alfa(x) e Alfa(COST) unificano con θ={x/COST}). T.",
    ('2','5'): "FC richiede clausole di Horn definite (regole). La formula data ha più letterali negativi → non è una Horn pulita per FC. F.",
    ('3','1'): "BFS con costi unitari è ottima (trova soluzione minima per numero di azioni) e completa.",
    ('3','2'): "DFS può perdersi su cammini infiniti, quindi NON COMPLETA in generale (lo è solo su spazi finiti).",
    ('3','3'): "A* usa f(n)=g(n)+h(n) — la funzione di valutazione informata classica.",
    ('3','4'): "IDS combina memoria O(b·d) di DFS con completezza/ottimalità (per costi unitari) di BFS.",
    ('4','1'): "Scacchi: nessuna casualità, vedi tutta la scacchiera → deterministico, informazione completa.",
    ('4','2'): "Backgammon: lancio dadi a ogni turno → stocastico. Vedi tutto → informazione completa.",
    ('4','3'): "Othello: senza randomness, scacchiera visibile → deterministico, informazione completa.",
    ('4','4'): "Poker: mescolata casuale (stocastico) e carte avversarie nascoste (informazione incompleta).",
    ('5','1'): "Negli scacchi vedi sempre tutto lo stato (scacchiera) → completamente osservabile.",
    ('5','2'): "Nel poker non vedi le carte degli avversari → parzialmente osservabile.",
    ('5','3'): "Classificatore di immagini: ogni immagine è episodio indipendente. La decisione su una non influenza le altre → episodico.",
    ('5','4'): "Backgammon ha lancio dadi → stocastico, non deterministico.",
    ('6','1'): "Schema standard CSP per N-regine: ogni regina è una variabile. Posizionarne una per colonna riduce vincoli ridondanti.",
    ('6','2'): "Dominio di ogni variabile = riga in cui posizionare la regina = {1..N}.",
    ('6','3'): "Vincoli binari: ogni coppia di regine non deve essere su stessa riga, colonna o diagonale.",
    ('6','4'): "Nei CSP la soluzione è l'ASSEGNAMENTO finale, non una sequenza di mosse (concetto di problem solving classico).",
    ('7','1'): "Spam detection con esempi etichettati spam/non-spam → supervisionato classico.",
    ('7','2'): "Segmentazione clienti senza etichette → clustering = non supervisionato.",
    ('7','3'): "Imparare giocando massimizzando punteggio = ricevi reward dall'ambiente → reinforcement learning.",
    ('7','4'): "LLM pre-training: predici la prossima parola dal contesto. Le 'etichette' sono i token del testo stesso → auto/self-supervised.",
    ('8','1'): "Accuratezza = (TP+TN)/totale = predizioni corrette/totale. Definizione standard.",
    ('8','2'): "Convenzione: righe = vero (reale), colonne = predetto. La diagonale principale = predizioni corrette.",
    ('8','3'): "Alta accuratezza SUL TRAINING può essere overfitting. Solo l'accuratezza su TEST set non visto è indicativa di generalizzazione.",
    ('8','4'): "La confidence è una proprietà del classificatore (es. probabilità output di softmax), non derivabile dalla sola matrice di confusione.",
    ('8','5'): "Error rate = predizioni sbagliate/totale = 1 - accuratezza. Per definizione.",
    ('9','1'): "Negli alberi di decisione i nodi INTERNI testano un attributo (es. 'Età > 30?'). Le foglie predicono la classe.",
    ('9','2'): "Le foglie corrispondono alla classe predetta per le istanze che vi arrivano. Sono il 'leaf label'.",
    ('9','3'): "Si preferisce l'attributo con MAGGIOR information gain (riduce di più l'incertezza). Minor gain = peggior split. F!",
    ('9','4'): "Entropia(t) = -Σ p log p. Se tutte le istanze sono in una classe, p=1, log(1)=0 → entropia 0. Nodo puro = entropia nulla.",
    ('9','5'): "Prepruning ferma la crescita quando il guadagno è sotto soglia. Tecnica classica per controllare overfitting durante la costruzione.",
    ('10','1'): "Perceptron lineare = iperpiano singolo. XOR richiede frontiera non lineare (2 iperpiani). Famoso limite di Minsky-Papert.",
    ('10','2'): "Cybenko/Hornik 1989: MLP con 1 hidden layer e attivazioni non-lineari approssima qualunque funzione continua su un compatto.",
    ('10','3'): "σ'(x) = σ(x)(1-σ(x)). Mai identicamente nulla; tende a 0 agli estremi (vanishing gradient).",
    ('10','4'): "Backprop = -η ∇L: si va nella direzione opposta al gradiente. Stessa logica della discesa del gradiente.",
    ('10','5'): "η troppo grande: passi che 'saltano' il minimo, oscillazione, divergenza. Tipico debug di NN che esplode in NaN.",
    ('11','1'): "L'albero di expectiminimax ha 4 tipi di nodi: max (MAX gioca), min (MIN gioca), terminali (esito noto), casuali (cerchi, variabile aleatoria).",
    ('11','2'): "Sì: V(nodo_casuale) = Σ_r P(r) · V(figlio_r). È valore atteso pesato.",
    ('11','3'): "Quando non ci sono nodi casuali (n=1 evento), expectiminimax = minimax. Caso degenere.",
    ('11','4'): "No: la complessità è O(b^m · n^m), peggiore di O(b^m) per la presenza di n eventi casuali per nodo.",
    ('12','1'): "Fluente = predicato/relazione il cui valore può cambiare nel tempo (con esecuzione di azioni). Concetto chiave del situation calculus.",
    ('12','2'): "L'assioma di frame esprime persistenza: ciò che NON è effetto di un'azione mantiene il suo valore. Risolve (in parte) il frame problem.",
    ('12','3'): "PDDL = Planning Domain Definition Language. Standard per definire planning problems (stati, azioni, goal).",
    ('12','4'): "L'anomalia di Sussman MOSTRA il CONTRARIO: i sottogoal possono essere INTERDIPENDENTI, perseguirli linearmente può disfarne altri.",
    ('13','1'): "Disjoint(S) = le categorie in S non hanno istanze comuni. È esattamente l'enunciato.",
    ('13','2'): "Partition(S,C) = Disjoint(S) ∧ ExhaustiveDec(S,C) per definizione formale.",
    ('13','3'): "ExhaustiveDec(S,C) richiede che le categorie di S coprano tutte le istanze di C (no istanze di C fuori da S).",
    ('13','4'): "Disjoint NON implica Exhaustive: posso avere categorie disgiunte ma che non coprono tutto C (es. {Cane, Gatto} è disgiunto ma non copre tutti gli animali).",
    ('14','1'): "Pongo è un individuo specifico, Dalmata è la categoria → Pongo è ISTANZA di Dalmata → Member.",
    ('14','2'): "Dalmata e Cane sono entrambe CATEGORIE; Dalmata sottoclasse di Cane → Is-a.",
    ('14','3'): "Tom = istanza, Bassotto = categoria → Member.",
    ('14','4'): "Bassotto e Cane = categorie; Bassotto sottoclasse di Cane → Is-a.",
    ('15','1'): "Manhattan domina 'tessere fuori posto': è sempre ≥ (perché conta passi reali, non solo presenza fuori posto). Ammissibile.",
    ('15','2'): "Tessere fuori posto è ammissibile (sottostima sempre) ma NON DOMINA Manhattan (è meno informativa). Ammissibile non dominante.",
    ('15','3'): "Costo medio × 10: nessuna garanzia di sottostima, può sovrastimare → NON ammissibile.",
    ('16','1'): "∀x (P(x)∨¬P(x)) è il terzo escluso quantificato → vera in ogni modello → VALIDA.",
    ('16','2'): "∃x (P(x)∧¬P(x)) afferma esista qualcosa che sia P e non-P → contraddizione → INSODDISFACIBILE.",
    ('16','3'): "∀x ∃y Ama(x,y) può essere vera in alcuni mondi (chi ama qualcuno) e falsa in altri (mondo senza amore) → soddisfacibile non valida.",
    ('17','1'): "Backtracking standard: assegna una variabile alla volta, torna indietro al primo conflitto.",
    ('17','2'): "Forward checking: dopo un assegnamento, controlla un vincolo alla volta ed elimina valori incompatibili dai domini futuri (consistenza locale rispetto al vincolo).",
    ('17','3'): "AC-3: verifica consistenza tra coppie di variabili (archi). Più potente di forward checking, propaga le restrizioni a coppie.",
    ('17','4'): "Backjumping: dal fallimento risale al nodo più recente CAUSA del conflitto (conflict-directed), saltando intermedi irrilevanti.",
    ('18','1'): "¬A∨¬B∨C: un solo letterale positivo (C) → HORN. Equivalente alla regola A∧B→C.",
    ('18','2'): "A∨B∨¬C: due letterali positivi (A,B) → NON Horn.",
    ('18','3'): "¬A: zero letterali positivi → HORN (caso 'no head', vincolo di non).",
    ('18','4'): "P (singolo positivo): UN letterale positivo, zero negativi → HORN (fact).",
    ('18','5'): "A∨B: due letterali positivi → NON Horn.",
    ('19','1'): "Policy π(a|s) assegna probabilità di ogni azione in ogni stato. Caso deterministico = una sola azione con probabilità 1.",
    ('19','2'): "Il reward indica COSA si vuole (obiettivo), NON COME farlo. Confonderli porta a reward hacking.",
    ('19','3'): "γ ∈ [0,1]. γ=0 → miope (solo reward immediato). γ=1 → tutti i reward futuri pesano uguali (problemi su orizzonti infiniti).",
    ('19','4'): "V^π(s) = E[Σ γ^k r_{t+k+1} | s_t = s, π] espressa ricorsivamente come r + γ V^π(s'). Equazione di Bellman.",
    ('20','1'): "n variabili booleane → 2^n combinazioni → 2^n - 1 parametri indipendenti (l'ultimo determinato dalla normalizzazione Σp = 1).",
    ('20','2'): "Definizione di indipendenza: P(X,Y) = P(X)P(Y). Equivalentemente P(X|Y)=P(X).",
    ('20','3'): "L'efficienza delle reti bayesiane viene proprio dallo sfruttare indipendenze condizionate: poche probabilità locali invece di una tabella esponenziale.",
    ('20','4'): "P(H|E) = P(E|H)P(H)/P(E). Inverte la direzione condizionale. È il teorema di Bayes.",
    ('21','1'): "Minimax assume entrambi i giocatori ottimi: MAX max, MIN min. Worst-case ragionamento.",
    ('21','2'): "α-β è una potatura SAFE: stesso risultato di minimax, solo più veloce. Non cambia mai il valore calcolato.",
    ('21','3'): "Con ordine perfetto delle mosse (best first), α-β ha complessità O(b^(m/2)) — radice del numero di nodi → doppia profondità a parità di tempo.",
    ('21','4'): "α-β è formulato per giochi a 2 giocatori a somma zero. Per più giocatori serve max^n, NON è applicabile direttamente.",
    ('22','1'): "Transformer/LLM: meccanismo principale è SELF-ATTENTION (multi-head). Calcola pesi di rilevanza tra tutti i token della sequenza.",
    ('22','2'): "GAN: generatore vs discriminatore in gioco MINIMAX (zero-sum). G inganna, D distingue.",
    ('22','3'): "Diffusion: processo iterativo di DENOISING. Si apprende a invertire l'aggiunta progressiva di rumore.",
    ('22','4'): "CNN: convoluzioni 2D con filtri condivisi, pensate per immagini sfruttando località e invarianza traslazionale.",
    ('23','1'): "La risoluzione opera su clausole; si trasforma tutta la KB in CNF (clausole) prima di iniziare.",
    ('23','2'): "Refutazione = dimostra per ASSURDO: aggiungi ¬goal alla KB e cerchi la contraddizione.",
    ('23','3'): "Successo = derivare la clausola vuota □ (contraddizione). Conclude che la KB originale implica il goal.",
    ('23','4'): "FALSO: derivare □ non significa che la KB originale era contraddittoria, ma che KB ∪ {¬goal} lo è. La KB originale può essere coerente; il successo della refutazione prova KB ⊨ goal.",
    ('24','1'): "Termostato: percepisce T<20 → accende. Regola IF-THEN. Reattivo semplice.",
    ('24','2'): "Auto autonoma mantiene mappa interna (SLAM) → STATO interno → basato su modello.",
    ('24','3'): "Pianificatore: ha goal esplicito, costruisce sequenza per raggiungerlo → goal-driven.",
    ('24','4'): "Massimizza profitto = funzione di utilità → utility-driven (più sofisticato di puramente goal-driven).",
    ('25','1'): "Pattern classico di overfitting: il modello memorizza il training ma non generalizza al test.",
    ('25','2'): "Prepruning ferma la crescita dell'albero quando guadagno < soglia → impedisce di adattarsi troppo ai dati di training.",
    ('25','3'): "FALSO: più parametri non implica migliore. Spesso porta a overfitting. Rasoio di Occam: preferisci modelli semplici.",
    ('25','4'): "Occam: a parità di prestazioni, modello più semplice è da preferire (interpretabilità, robustezza, generalizzazione).",
    ('26','1'): "{P,Q} e {¬P,R}: P e ¬P unificano direttamente. Risolvente: {Q,R}. T.",
    ('26','2'): "{P} e {Q,R}: nessun letterale opposto. Risoluzione NON applicabile. F.",
    ('26','3'): "P(a) e ¬P(x) unificano con θ={x/a}. Risolvente: clausola vuota. Risoluzione FOL con lifting. T.",
    ('26','4'): "P(a) e ¬P(b): a, b costanti distinte, NON unificabili. Risoluzione non applicabile. F.",
    ('27','1'): "Tassonomia: albero con relazioni Is-a (sottoclasse). Caso particolare di ontologia.",
    ('27','2'): "Bunch-of: oggetto composto da parti elencate, SENZA specificare le relazioni interne tra le parti.",
    ('27','3'): "T-box: concettualizzazione INTENSIONALE (definizioni di classi, proprietà generali).",
    ('27','4'): "A-box: fatti su singole istanze (estensione concreta di una T-box).",
    ('28','1'): "BFS: coda FIFO → first in, first out. I primi nodi inseriti (più superficiali) vengono espansi prima.",
    ('28','2'): "DFS: pila LIFO → last in, first out. Gli ultimi inseriti (più profondi) vengono espansi per primi.",
    ('28','3'): "Uniform-cost: coda con priorità su costo g(n). Si espande sempre il più 'economico'.",
    ('28','4'): "IDS: lancia DLS con limite di profondità incrementale 0,1,2,... Combina memoria DFS con completezza BFS.",
    ('29','1'): "Sigmoide σ(x) = 1/(1+e^(-x)): output in (0,1), derivabile ovunque. Storica per output binari.",
    ('29','2'): "Tanh: tanh(x) ∈ (-1,1), derivabile. Simmetrica intorno a 0, gradiente migliore di sigmoide negli strati profondi.",
    ('29','3'): "ReLU: max(0,x). Lineare a tratti, in [0,+∞). Computazionalmente economica, evita vanishing gradient per x>0. Non differenziabile in 0 (ma trattata operativamente).",
    ('29','4'): "Gradino classico del perceptron originale: H(x) = 1 se x>0 else 0. NON differenziabile in 0 (salto). Per questo non usabile con backprop.",
    ('30','1'): "A∨¬A: terzo escluso. Sempre vero. T.",
    ('30','2'): "A∧¬A: contraddizione. Mai vera. NON soddisfacibile → F.",
    ('30','3'): "A→B equivale a ¬A∨B per definizione di implicazione materiale. T.",
    ('30','4'): "Se KB⊨α allora KB∧¬α è INSODDISFACIBILE (definizione di entailment). 'Soddisfacibile' è F.",
}

def add_col(in_path, mapping):
    with open(in_path) as f:
        rows = list(csv.reader(f))
    header = rows[0] + ['explanation']
    out = [header]
    for r in rows[1:]:
        if in_path.endswith('mcq.csv'):
            key = r[0]
            expl = mapping.get(key, '(spiegazione non disponibile)')
        else:
            key = (r[0], r[1])
            expl = mapping.get(key, '(spiegazione non disponibile)')
        out.append(r + [expl])
    with open(in_path, 'w', newline='') as f:
        w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        w.writerows(out)
    return len(out) - 1

n_mcq = add_col('mcq.csv', MCQ)
n_mt = add_col('matching.csv', MATCHING)
print(f"mcq: {n_mcq} righe annotate")
print(f"matching: {n_mt} righe annotate")
# Find any missing
import csv as c2
with open('mcq.csv') as f:
    rows = list(c2.reader(f))
missing = [r[0] for r in rows[1:] if r[-1] == '(spiegazione non disponibile)']
print(f"MCQ senza spiegazione: {len(missing)} {missing}")
with open('matching.csv') as f:
    rows = list(c2.reader(f))
missing = [(r[0],r[1]) for r in rows[1:] if r[-1] == '(spiegazione non disponibile)']
print(f"Matching senza spiegazione: {len(missing)} {missing[:10]}")
