#!/usr/bin/env python3
"""Aggiunge colonna 'explanation' a mcq.csv e matching.csv."""
import csv

MCQ = {
    '1': "Pensa alla soluzione non solo come alla destinazione finale, ma come all'intero viaggio! Nei problemi di ricerca, conta il percorso (le mosse) che fai per arrivare all'obiettivo, non solo l'averlo raggiunto.",
    '2': "La ricerca 'cieca' si chiama così perché il sistema brancola nel buio: conosce solo le regole base del gioco e non ha nessun 'suggerimento' (euristica) su quale mossa sia migliore delle altre.",
    '3': "Un'euristica (una stima) 'domina' un'altra semplicemente se le sue stime sono sempre più alte e vicine al costo reale (senza mai superarlo). Più è alta, meno strade inutili esploreremo!",
    '4': "La matrice di confusione è una tabella che riassume gli errori e i successi di un modello. Da lì possiamo calcolare tutti i voti: quanto è accurato, quanti falsi allarmi ha dato, ecc.",
    '5': "L'apprendimento è 'supervisionato' quando diamo al computer i dati completi di soluzione. È come dare a uno studente gli esercizi già svolti con la risposta corretta, per insegnargli la regola.",
    '6': "L'IA si dice 'artificiale' semplicemente perché è costruita dall'uomo e non biologica. Può essere anche solo un software che gira su un computer normale.",
    '7': "Il Test di Turing in parole povere: se parli con qualcuno in chat e non riesci a capire se è un umano o un computer, allora quel computer ha superato il test ed è considerato intelligente.",
    '8': "L'IA 'debole' non significa che sia stupida, ma solo che finge di essere intelligente risolvendo compiti specifici, senza avere una vera coscienza o provare emozioni reali.",
    '9': "L'IA 'forte' è quella dei film di fantascienza: una macchina che ha una vera e propria coscienza, capisce davvero quello che fa e ha sentimenti.",
    '10': "L'esperimento della Stanza Cinese dimostra questo: se seguo un manuale di istruzioni per combinare simboli cinesi e dare risposte corrette, non significa che io abbia imparato il cinese. Stessa cosa per i computer!",
    '11': "Il CAPTCHA è il Test di Turing al contrario: è il computer che fa un test a te (es. farti cliccare sui semafori) per capire se sei un umano o un robot.",
    '12': "Deterministico significa 'senza sorprese'. Se in una situazione premo il bottone A, succederà sempre e infallibilmente la cosa X. Nessun fattore casuale.",
    '13': "Stocastico significa 'con un pizzico di fortuna'. Pensa a un gioco di dadi o a un robot che scivola: fai la stessa mossa, ma il risultato può variare a causa del caso.",
    '14': "In un ambiente episodico, la vita è una serie di test indipendenti. Quello che fai adesso non avrà nessuna conseguenza sulle sfide successive (al contrario degli scacchi, dove ogni mossa pesa sul futuro).",
    '15': "Ambiente statico significa che il mondo mette in pausa mentre pensi (come a scacchi). In un ambiente dinamico, invece, il mondo va avanti (come guidare un'auto nel traffico).",
    '16': "Parzialmente osservabile significa giocare a poker o muoversi nella nebbia: non hai tutte le informazioni sul tavolo a tua disposizione e devi tirare a indovinare.",
    '17': "In parole povere: Dichiarativo è quando descrivi COSA è il problema (specifica logica, vincoli). Imperativo/procedurale è quando descrivi COME risolverlo. Il dichiarativo permette di riusare lo stesso motore su problemi diversi cambiando solo la KB.",
    '18': "In parole povere: Definizione standard di Russell & Norvig. Agente è quando entità che PERCEPISCE tramite sensori e AGISCE tramite attuatori sull'ambiente. Astrazione cruciale: separa logica/conoscenza dall'implementazione fisica.",
    '19': "In parole povere: Autonomo è quando riceve obiettivi ad alto livello e decide autonomamente i passi. Si distingue dall'automazione (riceve istruzioni passo-passo). Autonomia richiede capacità di ragionamento e adattamento.",
    '20': "In parole povere: Mondo dei blocchi è quando problema didattico classico per illustrare planning/ricerca. Non è 'reale' nel senso applicativo; serve a mostrare concetti come stati, azioni, goal, in un dominio semplice e visualizzabile.",
    '21': "In parole povere: Formulazione di un problema è quando (S0, Actions, Transition Model, Goal Test, Path Cost). Il numero di iterazioni è una proprietà dell'algoritmo che lo risolve, NON del problema.",
    '22': "In parole povere: BFS visita per livelli di profondità crescenti, espandendo TUTTI i nodi di profondità d prima di quelli a d+1. Usa coda FIFO. Espansione profonda è quando DFS.",
    '23': "In parole povere: DFS espande sempre il nodo più profondo della frontiera. Usa pila LIFO (o ricorsione). Non è ottima: trova soluzione ma non necessariamente la più breve.",
    '24': "In parole povere: DFS NON è completa se il branching factor permette cammini infiniti (può perdersi su un ramo infinito senza mai esplorare altri). Lo è solo su grafi finiti senza cicli o con graph-search che tenga traccia dei visitati.",
    '25': "In parole povere: IDS combina la completezza/ottimalità di BFS (esplorazione per livelli) con la memoria lineare di DFS. Il costo è solo costante: riesplorare nodi superficiali è dominato dall'esplorazione del livello più profondo.",
    '26': "In parole povere: BFS espande TUTTI i nodi fino a profondità d. Con branching b ci sono b + b² + ... + b^d ≈ b^d nodi. Stessa complessità in spazio (memorizza la frontiera).",
    '27': "In parole povere: Uniform-cost (Dijkstra) espande il nodo con MINOR costo g(n) accumulato dall'inizio. Garantisce ottimalità con costi positivi. Diverso da BFS (che usa profondità) e da greedy (che usa h).",
    '28': "In parole povere: A* combina costo passato g(n) e stima futura h(n) in f(n) è quando g(n)+h(n). Il nodo espanso è sempre quello che minimizza il costo totale stimato della soluzione che passa per esso.",
    '29': "In parole povere: Con euristica ammissibile (non sovrastima il costo reale) e costi positivi, A* è completa e ottima usando tree-search. Per graph-search serve consistenza, altrimenti basta riaprire i nodi.",
    '30': "In parole povere: Ammissibilità è quando h(n) ≤ h*(n), dove h*(n) è il vero costo da n al goal. Garantisce che A* non potoni il cammino ottimo. Una h che sovrastima può far ignorare la soluzione migliore.",
    '31': "In parole povere: Consistenza (monotonia) è proprietà più forte di ammissibilità: per ogni arco (n,n') vale h(n) ≤ c(n,n') + h(n'). Implica che f sia non decrescente sui cammini e quindi A* con graph-search è ottima senza riapertura.",
    '32': "In parole povere: Dominanza è una relazione tra euristiche ammissibili: h2 ≥ h1 ovunque. Con h dominante A* espande meno nodi (a parità di ottimalità) perché stringe di più i bound.",
    '33': "In parole povere: RBFS imita best-first con backtracking ricorsivo: tiene in memoria solo il cammino corrente (memoria lineare in d), non l'intera frontiera. Trade-off: rivisita nodi quando il backtrack riapre rami già scartati.",
    '34': "In parole povere: Minimax è formulato per giochi a SOMMA ZERO, due giocatori (MAX/MIN) con perfetta informazione. Per giochi cooperativi o multi-giocatore servono varianti (max^n, ecc.).",
    '35': "In parole povere: Alfa-beta è una potatura SAFE: non cambia il valore minimax calcolato, ma evita di esplorare sottoalberi che non possono influenzare la decisione finale. Cambia solo l'efficienza.",
    '36': "In parole povere: Con ordinamento perfetto delle mosse (best first), alfa-beta visita solo b^(m/2) nodi invece di b^m. Permette di raddoppiare la profondità di ricerca a parità di tempo.",
    '37': "In parole povere: Un CSP è la tripla <X, D, C>: X è quando insieme di variabili, D è quando domini, C è quando vincoli (relazioni tra sottoinsiemi di variabili). Niente funzione obiettivo (sarebbe CSOP).",
    '38': "In parole povere: Soluzione di CSP è quando assegnamento completo che soddisfa TUTTI i vincoli. Non un cammino: nei CSP la sequenza di assegnamenti non importa, conta solo l'assegnamento finale.",
    '39': "In parole povere: Backtracking è quando DFS specializzato per CSP. Assegna variabili una alla volta; se viola un vincolo, torna indietro all'ultima scelta e prova un altro valore. Forward checking lo potenzia eliminando valori inconsistenti dai domini futuri.",
    '40': "In parole povere: Forward checking, dopo ogni assegnamento, elimina dai domini delle variabili future i valori inconsistenti con il vincolo attivo. Rileva precocemente fallimenti. Più debole di arc consistency (che considera anche vincoli tra variabili future).",
    '41': "In parole povere: AC-3 stabilisce ARC CONSISTENCY (2-consistency): ogni valore in ogni variabile è supportato da almeno un valore consistente in ciascun arco. Path consistency è quando 3-consistency, più costosa.",
    '42': "In parole povere: K-consistency: ogni assegnamento consistente a k-1 variabili può essere esteso a una k-esima variabile mantenendo la consistenza. Strong k-consistency è quando j-consistency per tutti j ≤ k. Costo cresce esponenzialmente con k.",
    '43': "In parole povere: Backjumping invece di tornare al genitore immediato, salta direttamente al nodo più recente i cui assegnamenti hanno causato il conflitto (conflict-directed). Riduce il backtrack inutile su variabili indipendenti.",
    '44': "In parole povere: Informata è quando usa un'euristica h(n) che stima il costo (o la distanza) per raggiungere il goal dal nodo n. La blind no, vede solo la struttura del problema senza guida di dominio.",
    '45': "In parole povere: Greedy best-first espande il nodo con h(n) minimo (la stima più bassa di distanza al goal). Veloce ma non considera il costo già speso, quindi può scegliere cammini lunghi che 'sembrano' vicini al goal.",
    '46': "In parole povere: Greedy può ciclare (non completo senza graph-search) e può scegliere cammini sub-ottimi perché ignora g(n). Esempio classico: Romania, da Iași a Fagaraș via Neamț (vicolo cieco).",
    '47': "In parole povere: IDDFS è completa su spazi con branching factor finito (anche se infinitamente profondi): per ogni profondità d esiste un'iterazione che la esplora. Su spazi infiniti in larghezza non lo è.",
    '48': "In parole povere: DFS usa O(b·m) memoria: solo il cammino corrente + fratelli non espansi. BFS deve memorizzare l'intera frontiera è quando O(b^d). Per d>>m questo è un trade-off enorme.",
    '49': "In parole povere: Funzione di valutazione è quando approssimazione di utilità per stati NON terminali. Permette di troncare la ricerca (depth-limited) e stimare chi sta vincendo. Negli scacchi: materiale + posizione + ecc.",
    '50': "In parole povere: Somma zero: utilità(MAX) + utilità(MIN) è quando costante. Ciò che uno guadagna l'altro perde. Permette di modellare il gioco con un'unica funzione utilità da massimizzare/minimizzare.",
    '51': "In parole povere: Minimax assume gioco ottimale di entrambi: MAX cerca max utilità, MIN cerca minimizzarla. Se l'avversario gioca male, minimax è ancora corretto (al peggio è quando al meglio per MAX) ma può non essere ottimo nella pratica.",
    '52': "In parole povere: Mappa con k colori, quindi CSP: variabili è quando regioni, domini è quando {1..k}, vincoli binari è quando regioni adiacenti hanno colori diversi. Classico problema NP-completo (per k=3 su grafi generali).",
    '53': "In parole povere: N-regine si modella come CSP: variabili è quando N regine (una per colonna), dominio è quando righe {1..N}, vincoli binari è quando nessuna stessa riga né diagonale. Risolvibile efficientemente con AC + backtracking.",
    '54': "In parole povere: Planning è quando costruire automaticamente una sequenza di azioni per raggiungere un goal a partire da uno stato iniziale, dato un modello delle azioni (precondizioni ed effetti).",
    '55': "In parole povere: Stocastici è quando giochi con componente aleatoria intrinseca (dadi, mescolata di carte): l'esito di un'azione non è deterministicamente prevedibile. Backgammon, briscola, poker.",
    '56': "In parole povere: Backgammon: ogni mossa è preceduta da lancio di 2 dadi che determina le mosse possibili. Componente aleatoria forte. Scacchi e othello sono deterministici.",
    '57': "In parole povere: Expectiminimax estende minimax aggiungendo NODI DI CASUALITÀ tra mosse di MAX e MIN. Il valore di un nodo casuale è la media pesata (per probabilità) dei valori dei figli.",
    '58': "In parole povere: Per applicare expectiminimax devo conoscere la percentuali di probabilità di ogni evento casuale (es. probabilità di ogni combinazione dei dadi 1/36 ciascuna nel backgammon).",
    '59': "In parole povere: Nodo casuale: V(s) è quando Σ_r P(r) · expectiminimax(result(s,r)). È un'aspettazione, non un max né min. Riflette l'incertezza sull'esito.",
    '60': "In parole povere: Complessità expectiminimax è O(b^m · n^m) dove n è quando numero esiti casuali per nodo. Esponenziale in più rispetto a minimax: i nodi casuali moltiplicano il branching.",
    '61': "In parole povere: Alfa-beta in expectiminimax è difficile: i nodi casuali calcolano medie, quindi non c'è un bound certo come max o min. Esiste *probabilistic alpha-beta* ma richiede bound sui valori delle utility.",
    '62': "In parole povere: Variabile aleatoria è quando mappa da uno spazio campionario a un valore (numero, categoria). Il suo valore dipende dall'esito di un fenomeno aleatorio. Esempi: lancio di dado, colore di pallina estratta.",
    '63': "In parole povere: Le due fonti tipiche di incertezza per un agente: (1) conoscenza imperfetta delle regole del mondo, (2) osservabilità parziale (sensori non vedono tutto). Entrambe vanno modellate per agire razionalmente.",
    '64': "In parole povere: Rappresentazione della conoscenza è quando formalizzare fatti sul mondo in modo che un sistema possa ragionare automaticamente su di essi (inferenza, query answering, verifica consistenza).",
    '65': "In parole povere: Formula atomica in logica proposizionale è quando una singola variabile proposizionale (es. P, Piove). È l'unità base; congiunzioni o clausole sono formule composte.",
    '66': "In parole povere: Letterale è quando formula atomica (positiva, es. P) o sua negazione (negativa, es. ¬P). È il mattone base delle clausole.",
    '67': "In parole povere: Clausola è quando DISGIUNZIONE di letterali (l1 ∨ l2 ∨ ... ∨ ln). Le clausole vuote (= falso) e unitarie (= un solo letterale) sono casi limite. La CNF è congiunzione di clausole.",
    '68': "In parole povere: CNF è quando congiunzione di clausole (= ∧ di ∨). Ogni formula proposizionale può essere trasformata in CNF equivalente. Forma normale richiesta dalla risoluzione.",
    '69': "In parole povere: Tautologia è quando vera in OGNI interpretazione/modello (esempio: A ∨ ¬A). Concettualmente: verità logica indipendente dal mondo specifico.",
    '70': "In parole povere: Contraddizione è quando falsa in ogni interpretazione (es. A ∧ ¬A). Una KB contraddittoria implica tutto (ex falso quodlibet) — pessima!",
    '71': "In parole povere: Soddisfacibile è quando esiste ALMENO un'interpretazione che la rende vera. Diverso da valida (vera in tutte) e da insoddisfacibile (vera in nessuna).",
    '72': "In parole povere: Clausola di Horn è quando clausola con AT MOST UN letterale positivo. Forme: solo negativi (¬A∨¬B), una positiva pura (P), regola (¬A∨¬B∨C ≡ A∧B→C). Permette inferenza efficiente lineare (Prolog).",
    '73': "In parole povere: Modus ponens: da A e A→B deduco B. Regola fondamentale della logica deduttiva. Forward chaining la applica iterativamente sui fatti noti.",
    '74': "In parole povere: Risoluzione proposizionale è REFUTATION-COMPLETE: deriva la clausola vuota da KB ∧ ¬α se e solo se KB ⊨ α. Non genera direttamente TUTTE le conseguenze ma ne verifica una qualsiasi.",
    '75': "In parole povere: Refutazione è quando dimostrare per assurdo. Per provare KB ⊨ α, aggiungo ¬α alla KB e applico risoluzione: se derivo la clausola vuota (contraddizione), allora KB ⊨ α.",
    '76': "In parole povere: Forward chaining è quando data-driven. Parte dai fatti, applica regole le cui premesse sono soddisfatte, deriva nuovi fatti. Si ferma quando non c'è più nulla da derivare o si trova il goal. Efficiente per Horn KB.",
    '77': "In parole povere: Backward chaining è quando goal-driven. Parte dal goal, cerca regole che lo concludono e tenta di soddisfarne le premesse ricorsivamente. È il modello di Prolog.",
    '78': "In parole povere: FOL aggiunge: variabili, quantificatori (∀, ∃), predicati n-ari, funzioni. È strettamente più espressiva della proposizionale (può parlare di oggetti, non solo proposizioni atomiche).",
    '79': "In parole povere: ∀x P(x): per QUALSIASI scelta di x nel dominio, P(x) è vera. Universale è quando afferma una proprietà comune a tutto il dominio.",
    '80': "In parole povere: ∃x P(x): esiste ALMENO UN x nel dominio per cui P(x) è vera. Non specifica quale. Si combinano nidificandoli (∀x ∃y ≠ ∃y ∀x).",
    '81': "In parole povere: Formula ground è quando senza variabili libere o legate, solo costanti e funzioni applicate a costanti. È una formula 'concretamente vera o falsa' una volta fissata l'interpretazione.",
    '82': "In parole povere: Unificatore è quando sostituzione θ che, applicata a due espressioni (es. atomi), le rende sintatticamente identiche. Es: θ={x/John} unifica P(x) con P(John).",
    '83': "In parole povere: MGU (Most General Unifier) è l'unificatore meno specifico: ogni altro unificatore può essere ottenuto da MGU per ulteriore sostituzione. L'algoritmo di unificazione di Robinson trova sempre l'MGU se esiste.",
    '84': "In parole povere: Lifting è quando trasportare la risoluzione dalla proposizionale alla FOL: invece di chiedere uguaglianza tra letterali opposti, si chiede unificabilità tramite un MGU, che viene poi applicato alla clausola risolvente.",
    '85': "In parole povere: Binary resolution + factoring (collassare letterali unificabili) è REFUTATION-COMPLETE in FOL: se KB ⊨ α allora la risoluzione deriva la clausola vuota da KB ∧ ¬α (Robinson 1965).",
    '86': "In parole povere: Skolemizzazione: rimuove ∃ introducendo costanti (se ∃ è esterno) o funzioni di Skolem dipendenti dalle ∀ a sinistra. Es: ∀x ∃y Ama(x,y), quindi ∀x Ama(x, f(x)). Preserva soddisfacibilità (ma NON equivalenza).",
    '87': "In parole povere: KB è quando insieme strutturato di formule (assiomi, regole, fatti) che rappresenta conoscenza in un dominio. Cuore di un sistema basato su conoscenza/inferenza.",
    '88': "In parole povere: Interrogare è quando chiedere se una formula α è conseguenza logica della KB (KB ⊨ α?). Non si modifica la KB; si applica un motore inferenziale.",
    '89': "In parole povere: Tassonomia è quando struttura ad albero di categorie collegate da relazioni di sotto/super-classe (is-a). Ogni categoria eredita proprietà dai padri. Esempio: regno animale.",
    '90': "In parole povere: Is-a(A,B) tipicamente indica che A è SOTTOCLASSE di B (relazione tra categorie). Diverso da Member, che è relazione istanza-categoria.",
    '91': "In parole povere: Member(X,C) è quando X è un'ISTANZA (elemento) della categoria C. È relazione individuo-categoria. Diverso da Is-a (categoria-categoria).",
    '92': "L'ereditarietà è come la genetica: se definisci che la classe 'Uccelli' sa volare, tutte le sottoclassi (Pappagallo, Aquila) 'ereditano' automaticamente la capacità di volare senza doverlo riscrivere.",
    '93': "In parole povere: Disjoint(S) significa che le categorie in S non hanno istanze in comune (mutua esclusione). Es: {Cane, Gatto} sono disgiunte come categorie di mammiferi domestici.",
    '94': "In parole povere: ExhaustiveDec(S,C) è quando ogni istanza di C appartiene ad almeno una categoria di S (decomposizione che copre tutto C, ma può avere sovrapposizioni).",
    '95': "Creare una 'Partizione' significa dividere un gruppo in categorie che non si accavallano mai (un elemento sta in una e una sola categoria) e che coprono tutti (nessuno resta fuori).",
    '96': "In parole povere: Part-of è transitiva: se A è parte di B e B è parte di C, allora A è parte di C. Esempio: dito, quindi mano, quindi braccio, quindi corpo. NON è riflessiva (X non è parte di se stessa).",
    '97': "In parole povere: Bunch-of({a,b,c}) è quando oggetto composto dalle parti elencate, senza specificare le relazioni interne (a differenza di un'aggregazione strutturata). Es: un mucchio di pietre.",
    '98': "OWL (Ontology Web Language) e' il linguaggio dichiarativo del semantic web: definisce ontologie con entita' (riferimenti a oggetti del mondo reale), assiomi (gli statement di base) ed espressioni (combinazioni di entita' che formano descrizioni complesse).",
    '99': "In RDF ogni informazione e' una tripla soggetto-predicato-oggetto: il predicato mette in relazione soggetto e oggetto, e tutti e tre sono IRI (identificatori, es. URL). Un insieme di triple forma un grafo RDF; RDF e' la base di OWL e SKOS.",
    '100': "Nell'allineamento ontologico la strong-translatability e' il caso 'forte': tutto il vocabolario di O_source si mappa in O_dest, gli assiomi continuano a valere, non si perde informazione e non si introducono inconsistenze. Se c'e' perdita e' solo weakly-translatable.",
    '101': "In parole povere: Ontologia è quando grafo generale di concetti e relazioni (anche non gerarchiche: part-of, causes, ecc.). Tassonomia è quando caso particolare ad albero, con sole relazioni di sotto-classe.",
    '102': "In parole povere: OWL (Web Ontology Language) è quando linguaggio standard W3C per ontologie del semantic web. Basato su RDF, descrive classi, proprietà, individui con espressività descrizione-logica.",
    '103': "In parole povere: RDF rappresenta conoscenza come TRIPLE soggetto-predicato-oggetto. Es: <Pongo, hasOwner, Pongo's owner>. Un insieme di triple è un grafo RDF (nodi=entità, archi=predicati).",
    '104': "In parole povere: Fluente è quando predicato/relazione che dipende dalla situazione (cambia nel tempo). Es: Holds(At(Robot,L), s). Si denota esplicitamente la situazione s come argomento.",
    '105': "In parole povere: Assioma di applicabilità: ∀params,s Applicable(Action(params), s) ⇔ Precond(params, s). Definisce quando un'azione si può eseguire (precondizioni soddisfatte nella situazione corrente).",
    '106': "In parole povere: Assioma di effetto descrive cosa CAMBIA dopo l'azione: cosa è vero in Result(Action, s). Es: dopo Pickup(blocco) vale Holding(blocco). Non basta: c'è anche il frame problem.",
    '107': "In parole povere: Frame problem: come specificare che TUTTO IL RESTO non cambia? Non basta dire cosa cambia: serve dichiarare implicitamente o esplicitamente la persistenza degli altri fluenti.",
    '108': "In parole povere: Assioma di frame: per ogni fluente, dice che se nessun effetto lo modifica, mantiene il valore. Approccio classico: un assioma per ogni coppia (fluente, azione). Russell-McCarthy successor-state axioms compattano.",
    '109': "In parole povere: Anomalia di Sussman: perseguire un sottogoal può disfare un sottogoal già risolto (esempio classico con tre blocchi). Mostra che la pianificazione non sempre è lineare/sequenziale.",
    '110': "In parole povere: PDDL (Planning Domain Definition Language) standardizza la rappresentazione di problemi di planning: stati come fluenti, azioni con precondizioni ed effetti, goal. Usato in competizioni IPC.",
    '111': "In parole povere: Agente razionale (Russell-Norvig): sceglie l'azione che MASSIMIZZA L'UTILITÀ ATTESA data la sua percezione/conoscenza. Razionalità ≠ onniscienza: razionale può ancora sbagliare per limiti di info.",
    '112': "In parole povere: Reattivo semplice: input è quando percezione corrente, output è quando azione (regole IF-THEN-ELSE). Niente memoria né modello. Veloce ma cieco se servono stati passati.",
    '113': "In parole povere: Basato su modello: mantiene uno STATO INTERNO che riflette aspetti non osservati. Aggiorna lo stato in base a percezioni + modello di transizione. Necessario in ambienti parzialmente osservabili.",
    '114': "In parole povere: Goal-driven: ha un obiettivo esplicito. Sceglie azioni che lo avvicinano al goal (può usare planning). Più flessibile di reattivi puri: cambi goal, quindi cambi comportamento.",
    '115': "In parole povere: Utility-driven: ha una funzione di utilità sugli stati. Sceglie azioni che massimizzano l'utilità attesa. Permette di scegliere tra goal in conflitto (trade-off) e gestire incertezza.",
    '116': "In parole povere: Agente che apprende ha 4 componenti: elemento di esecuzione, elemento di apprendimento, MODULO CRITICO (valuta prestazioni e fornisce feedback), generatore di problemi (esplorazione).",
    '117': "In parole povere: Classificazione è quando assegnare un'istanza a una classe da un insieme PREDEFINITO di classi. Apprendimento supervisionato (training con classi note). Diverso da clustering (no etichette) e regressione (output continuo).",
    '118': "In parole povere: Supervisionato è quando i dati di training contengono coppie (input, classe). L'algoritmo impara la mappa input→classe. Apprendimento 'guidato' dalle etichette.",
    '119': "In parole povere: Non supervisionato (clustering) è quando senza etichette di classe. L'algoritmo trova STRUTTURE/GRUPPI naturali nei dati basandosi su similarità. Esempi: k-means, DBSCAN.",
    '120': "In parole povere: Test set è quando dati MAI VISTI durante training. Serve per stimare la generalizzazione del modello (prestazioni su dati nuovi). Confonderlo con training porta a stime ottimistiche.",
    '121': "In parole povere: Accuratezza è quando (TP+TN)/totale è quando predizioni corrette / totale. Misura globale di prestazione, sensata se le classi sono bilanciate. Su classi sbilanciate, va integrata con precision/recall.",
    '122': "In parole povere: Error rate è quando 1 − accuratezza è quando predizioni sbagliate / totale. Spesso più intuitivo quando vuoi minimizzare l'errore.",
    '123': "In parole povere: Matrice dei costi: a ogni cella (classe_reale, classe_predetta) associa un costo. Permette di pesare diversamente gli errori (es. falso negativo medico più grave del falso positivo).",
    '124': "In parole povere: Rote learning è quando memorizzare le istanze. Su nuova istanza cerca quella identica (o più simile via distanza). Semplice ma limitato; antenato di k-NN.",
    '125': "In parole povere: Voto a maggioranza: tra i vicini più simili, si conta la classe più frequente. Approccio base di k-NN. Adatto per classi discrete.",
    '126': "In parole povere: Voto pesato: ogni vicino contribuisce con un peso inversamente proporzionale alla distanza. Più vicino è quando più peso. Riduce l'influenza dei vicini lontani.",
    '127': "In parole povere: Albero di decisione: nodi interni testano un attributo, archi è quando valori dell'attributo, foglie è quando classe predetta. Modello interpretabile, ottenuto top-down con algoritmi tipo Hunt/ID3/C4.5.",
    '128': "In parole povere: Hunt: ricorsivo, top-down. (1) Se istanze nel nodo sono pure, quindi foglia. (2) Altrimenti scegli attributo migliore, splitta, ricorsivo sui figli. Variazioni differiscono nel criterio di scelta dell'attributo (gain).",
    '129': "In parole povere: Continui sono tipici negli alberi di decisione MA richiedono discretizzazione/scelta di soglie. Binari, nominali, ordinali sono direttamente trattabili. La distrazione 'continui' come 'non tipico' è giustificata solo se intendiamo nativi senza preprocessing.",
    '130': "In parole povere: Entropia(t) è quando -Σ p(i|t) log₂ p(i|t). Misura l'IMPURITÀ del nodo: 0 se tutte istanze stessa classe, max è quando log₂(c) se uniforme. Negli split si minimizza l'entropia attesa.",
    '131': "In parole povere: Information gain è quando entropia(padre) - Σ (|figlio|/|padre|) × entropia(figlio). Misura quanto un attributo RIDUCE l'incertezza. Si sceglie l'attributo con gain massimo.",
    '132': "In parole povere: Occam: a parità di prestazioni, preferisci il modello PIÙ SEMPLICE (minor numero di assunzioni). Negli alberi: meno nodi a parità di accuratezza. Riduce overfitting e migliora interpretabilità.",
    '133': "In parole povere: Overfitting: alta accuratezza su training, scarsa su test. Il modello ha imparato anche il rumore. Tipico in alberi troppo profondi, reti troppo grandi, training set piccolo.",
    '134': "In parole povere: Prepruning: interrompe lo split se il gain è sotto soglia o se il nodo è troppo piccolo. Previene overfitting MA può fermarsi troppo presto (sotto-apprendimento).",
    '135': "In parole povere: Postpruning: prima costruisci albero completo, poi POTI i rami che non migliorano prestazioni stimate (es. tramite validation set o pessimistic error). Più costoso ma più affidabile del prepruning.",
    '136': "In parole povere: MDL (Minimum Description Length): seleziona il modello che minimizza L(modello) + L(dati|modello). Bilancia complessità del modello e errore sui dati. Formalizza il rasoio di Occam.",
    '137': "In parole povere: Perceptron: net è quando Σwᵢxᵢ, output è quando f(net) con f è quando funzione di attivazione (originariamente gradino, poi sigmoide). Calcola una soglia su una combinazione lineare degli input.",
    '138': "In parole povere: Perceptron a singolo strato risolve solo problemi LINEARMENTE SEPARABILI. XOR non lo è (no iperpiano che separa (0,1),(1,0) da (0,0),(1,1)). Limite famoso evidenziato da Minsky&Papert.",
    '139': "In parole povere: Sigmoide σ(x) è quando 1/(1+e^(-x)): differenziabile, output (0,1), comportamento simile al gradino ma 'liscio'. Permette backpropagation (gradient computable).",
    '140': "In parole povere: MLP è quando perceptron multistrato con uno o più strati hidden tra input e output. Connessioni feed-forward, attivazioni non lineari. Universal approximator (Cybenko 1989).",
    '141': "In parole povere: Backpropagation: errore calcolato in output, propagato all'indietro attraverso lo strato hidden tramite chain rule. Si aggiornano i pesi proporzionalmente al gradiente del costo.",
    '142': "In parole povere: Discesa del gradiente: muoviti nello spazio dei pesi nella direzione OPPOSTA al gradiente della funzione di costo. Converge a minimo locale; learning rate controlla la velocità.",
    '143': "In parole povere: Learning rate η: passo dell'aggiornamento Δw è quando -η ∇L. Troppo alto, quindi oscillazioni/divergenza. Troppo basso, quindi convergenza lenta. Spesso si usano schedule (decay) o adattivi (Adam).",
    '144': "In parole povere: Un'epoca è quando una passata completa su tutto il learning set. Tipicamente si usano molte epoche (decine-migliaia). Diverso da iterazione (= un singolo aggiornamento mini-batch).",
    '145': "In parole povere: Rete neurale è quando approssimatore universale di funzioni: con neuroni e strati sufficienti può approssimare qualsiasi funzione continua. Natura distribuita: conoscenza in pesi, non in regole esplicite.",
    '152': "In parole povere: Clustering è quando trovare gruppi naturali in dati NON ETICHETTATI. Misura di similarità/distanza determina i cluster. Es: k-means minimizza distanza intra-cluster.",
    '153': "In parole povere: K-means: (1) inizializza k centroidi, (2) assegna ogni punto al centroide più vicino, (3) ricalcola centroidi come media dei punti assegnati, (4) ripeti fino a convergenza. Minimizza WSS (within-cluster sum of squares).",
    '154': "In parole povere: k è quando iperparametro fissato a priori. Sceglierlo male produce cluster poco significativi. Metodi: elbow, silhouette, gap statistic per stimare k buono.",
    '156': "In parole povere: Rule learning: produce un set di regole IF-THEN simboliche. Tecniche: sequential covering (RIPPER, CN2), conversione da albero di decisione. Vantaggio: regole sono leggibili.",
    '157': "In parole povere: Da albero a regole: ogni cammino radice-foglia, quindi una regola (premesse è quando test, conclusione è quando classe della foglia). Permette di interpretare l'albero come sistema di regole equivalente.",
    '158': "In parole povere: CNN: convoluzioni applicano filtri locali condivisi su immagini. Sfruttano invarianza traslazionale e località: pochi parametri rispetto a MLP fully-connected. Standard per visione (ImageNet, ecc.).",
    '159': "In parole povere: RNN/LSTM/GRU: condividono pesi nel tempo, stato nascosto h_t aggiornato a ogni timestep. Adatte a sequenze (testo, audio, serie storiche). LSTM/GRU gestiscono long-range con gating.",
    '160': "In parole povere: Transformer (Vaswani 2017): SELF-ATTENTION calcola pesi di rilevanza tra tutti gli elementi della sequenza. No ricorrenza, quindi parallelizzabile. Base di BERT, GPT, T5, ecc.",
    '161': "In parole povere: IA generativa: modelli che apprendono p(x) (o p(x|condizione)) e poi CAMPIONANO nuovi dati realistici. Diversa da discriminativa (apprende p(y|x) per classificare).",
    '162': "In parole povere: LLM è quando grande rete (Transformer) pre-addestrata su corpus enormi tramite next-token prediction. Apprendono distribuzione di linguaggio, generalizzano via few-shot/zero-shot prompting. Es: GPT, Llama.",
    '163': "In parole povere: GAN: generatore G crea fake, discriminatore D distingue reali/fake. Si addestrano in gioco MINIMAX: G inganna D, D smaschera G. All'equilibrio G produce campioni indistinguibili dai reali.",
    '164': "In parole povere: Autoencoder: rete encoder→bottleneck→decoder che impara a RICOSTRUIRE l'input. Il bottleneck è una rappresentazione compressa. Varianti: denoising, VAE (generativo), sparse.",
    '165': "In parole povere: Modelli di diffusione (DDPM): apprendono a invertire un processo che aggiunge rumore gaussiano gradualmente. Generano denoising step-by-step da rumore puro. Stato dell'arte per immagini (Stable Diffusion, DALL-E).",
    '166': "In parole povere: Variabile aleatoria in teoria probabilità: ha dominio (insieme di valori possibili) e distribuzione (probabilità su quel dominio). Discreta o continua. Concetto base prima di reti bayesiane.",
    '167': "La funzione di probabilita' associa a ogni evento un valore tra 0 e 1, e la somma delle probabilita' di tutti gli esiti dello spazio campionario vale esattamente 1.",
    '168': "La regola del prodotto scompone una congiunzione: P(e and c) = P(e|c)*P(c). L'uguaglianza P(e)*P(c) vale solo se evento e contesto sono indipendenti, non in generale.",
    '169': "La probabilità condizionata risponde alla domanda: 'Sapendo che è già successa la cosa B, quante probabilità ho che succeda A?'. È il modo in cui aggiorniamo le nostre credenze man mano che scopriamo nuovi indizi.",
    '170': "In parole povere: Bayes: P(H|E) è quando P(E|H)·P(H)/P(E). Inverte la condizionale: da P(evidenza|ipotesi) ricavi P(ipotesi|evidenza). Cuore dell'inferenza diagnostica.",
    '171': "In parole povere: X e Y indipendenti ⇔ P(X,Y) è quando P(X)·P(Y) ⇔ P(X|Y) è quando P(X). L'informazione su Y non cambia la probabilità di X. Forte assunzione spesso violata, da verificare.",
    '172': "In parole povere: X ⊥ Y | Z ⇔ P(X,Y|Z) è quando P(X|Z) · P(Y|Z). Indipendenza CONDIZIONATA: sapendo Z, sapere Y non aggiunge informazione su X. Chiave dell'efficienza delle reti bayesiane.",
    '173': "In parole povere: Rete bayesiana è quando DAG (Directed Acyclic Graph) + CPT (Conditional Probability Tables) per ogni nodo dato i genitori. Rappresenta compactamente distribuzioni congiunte sfruttando indipendenze condizionate.",
    '174': "In parole povere: Chain rule per reti bayesiane: P(X1,...,Xn) è quando Π_i P(Xi | parents(Xi)). Fattorizza la congiunta in prodotto di CPT locali. Esponenzialmente più compatta della tabella completa.",
    '175': "In parole povere: CPT di un nodo X è quando distribuzione P(X | Parents(X)) per ogni combinazione dei valori dei genitori. Per nodo binario con k genitori binari: 2^k righe, ognuna con 1 parametro.",
    '176': "In parole povere: Vantaggio reti bayesiane: indipendenze condizionate riducono i parametri. Congiunta completa è quando 2^n-1 parametri; rete con max k genitori è quando O(n·2^k). Compattezza esponenziale.",
    '177': "In parole povere: KR si occupa di formalizzare conoscenza affinché un sistema RAGIONI automaticamente. Include scelta del linguaggio (FOL, DL, OWL), strutturazione (ontologie), inferenza, gestione incertezza/incompletezza.",
    '178': "is-a(C1,C2) lega due categorie dicendo che C1 e' sottocategoria di C2; Member(P,C) e' vero quando P e' un elemento (istanza) della categoria C.",
    '179': "Un'ontologia si interroga chiedendo cose come: un'istanza appartiene a una categoria? gode di una proprieta'? che differenza c'e' tra due categorie? quali istanze esistono?",
    '180': "Il passaggio da World-Wide Web a Semantic Web aggiunge metadati ai contenuti pubblicati, cosi' che le macchine possano interpretarli, fare inferenza e interrogarli automaticamente. RDF ne e' il linguaggio di base.",
    '181': "In parole povere: Scacchi: informazione COMPLETA (vedi tutta la scacchiera), DETERMINISTICO (mosse senza casualità), SOMMA ZERO (vince uno o l'altro o patta), DUE giocatori. Caso ideale di minimax.",
    '182': "In parole povere: Poker: informazione INCOMPLETA (non vedi le carte avversarie), stocastico (ordine mescolata). Richiede ragionamento su belief states e bluffing — diverso da minimax classico.",
    '183': "In parole povere: Tessere fuori posto: ammissibile (ogni tessera fuori posto richiede ≥1 mossa). Sottostima la distanza Manhattan. È più 'sciocca' di Manhattan ma sufficiente per garantire ottimalità di A*.",
    '184': "In parole povere: Manhattan è quando somma delle distanze L1 di ogni tessera dalla posizione goal. Ammissibile (somma di lower bound) e DOMINA 'tessere fuori posto' (più informativa). Risultato classico AIMA.",
    '185': "In parole povere: Se h1 e h2 sono ammissibili, max(h1,h2) è ancora ammissibile (resta ≤ h*) e domina entrambe. Tecnica standard: combina euristiche diverse per ottenere un bound più stretto.",
    '186': "In parole povere: KB consistente ⇔ ha almeno un modello (un'interpretazione che la rende vera). KB inconsistente implica logicamente qualsiasi cosa (ex falso quodlibet) — inutilizzabile.",
    '187': "In parole povere: Valida è quando vera in OGNI modello è quando tautologia. Esempi: A∨¬A, ∀x(P(x)∨¬P(x)). Sintatticamente decidibili in proposizionale, semi-decidibili in FOL.",
    '188': "In parole povere: In FOL, una funzione f(t1,...,tn) DENOTA un elemento del dominio (es. madre_di(Carlo), quindi Anna). Diverso dai predicati che denotano valori di verità.",
    '189': "In parole povere: Predicato P(t1,...,tn) restituisce vero/falso. Funzione restituisce un oggetto del dominio. Distinzione cruciale in FOL: i predicati formano formule, le funzioni formano termini.",
    '190': "In parole povere: Differenza chiave: nel supervisionato i dati sono etichettati (input, classe), nel non-supervisionato no. Determina il tipo di task possibili e gli algoritmi applicabili.",
    '191': "In parole povere: Bassissimo training error + alto test error è quando overfitting tipico. Il modello ha imparato pattern specifici (incluso rumore) del training set, non generalizzabili.",
    '192': "In parole povere: Underfitting: il modello è troppo semplice per catturare la struttura dei dati. Errore alto su training E test. Soluzione: modello più espressivo, più feature, più dati di qualità.",
    '193': "In parole povere: Bias-variance trade-off: bias è quando errore sistematico (modello troppo rigido), variance è quando sensibilità al campione (modello troppo flessibile). Ridurre uno aumenta l'altro. Errore atteso è quando bias² + var + irriducibile.",
    '194': "In parole povere: Cross-validation: dividi dati in k fold, addestra su k-1 e valida sul k-esimo, ripeti k volte. Media le metriche. Stima più stabile dell'accuratezza su test set unico. Standard: 5-fold, 10-fold.",
    '195': "In parole povere: Gini(t) è quando 1 - Σ p(i|t)². Misura impurità alternativa all'entropia. Più rapida (no log). Tendenze simili. CART usa Gini, ID3/C4.5 usano gain ratio (basato su entropia).",
    '196': "In parole povere: Risoluzione richiede formule in CNF (congiunzione di clausole). Trasformazione: elimina implicazioni, sposta ¬ verso atomi, distribuisci ∨ su ∧. In FOL: Skolemizza prima.",
    '197': "Per definire un problema in modo che un computer lo risolva servono 5 ingredienti: da dove parto, dove voglio arrivare, quali mosse posso fare, cosa succede se faccio una mossa, e quanto mi costa ogni mossa.",
    '198': "In parole povere: Graph-search mantiene un insieme 'explored' di stati già visitati per evitare di rivisitarli. Critico per spazi con cicli o cammini multipli verso stessi stati. Tree-search no, e può ciclare.",
    '199': "In parole povere: Tecnica del problema rilassato: rimuovi vincoli del problema originale, risolvilo (più facile), usa il costo ottimale come euristica del problema vero. Garantisce ammissibilità.",
    '200': "Ricorda questo trucco logico: dire 'Se piove allora prendo l'ombrello' (A -> B) è esattamente identico a dire 'O non piove, o prendo l'ombrello' (Non A oppure B). È una regola d'oro per semplificare le formule.",
    '201': "In parole povere: Equivalenza ↔ è doppia implicazione: A↔B è quando (A→B)∧(B→A) è quando (¬A∨B)∧(¬B∨A). Trasformazione standard nelle conversioni in CNF.",
    '202': "In parole povere: ∀x (Cane(x)→Animale(x)): per ogni x del dominio, se è cane allora è animale. Schema standard per esprimere relazioni di sottoclasse in FOL.",
    '203': "In parole povere: Skolem per ∃ sotto ∀: ∀x ∃y P(x,y), quindi ∀x P(x, f(x)). La f dipende da x perché y può variare al variare di x. Preserva soddisfacibilità (non equivalenza).",
    '204': "In parole povere: ¬A ∨ ¬B ∨ C ha UN solo letterale positivo (C). Quindi è clausola di Horn. Equivale alla regola A ∧ B, quindi C.",
    '205': "In parole povere: Le Horn permettono FC/BC LINEARI nella dimensione della KB. Forma 'naturale' delle regole (premesse→conclusione). Cuore di Prolog. Limitazione: non esprimibile A∨B senza condizioni.",
    '206': "In parole povere: Distribuzione congiunta su n variabili booleane ha 2^n combinazioni; servono 2^n - 1 parametri (uno è vincolato dalla normalizzazione). Crescita esponenziale — impraticabile per n grande.",
    '207': "Semantica locale: noti i genitori di un nodo, quel nodo e' condizionalmente indipendente da tutti i suoi non-discendenti. E' equivalente alla semantica globale (la congiunta come prodotto delle condizionali locali).",
    '208': "In parole povere: Compactness BN: ogni nodo binario con al più k genitori contribuisce 2^k parametri. Totale n·2^k vs 2^n della congiunta completa. Esponenzialmente più piccolo se k << n.",
    '209': "In parole povere: Perceptron classico apprende SOLO funzioni linearmente separabili (esiste un iperpiano che separa le due classi). La sua regola di apprendimento converge in questo caso (teorema di Rosenblatt).",
    '210': "In parole povere: Iperpiano in n dimensioni: w·x è quando θ. Sopra l'iperpiano (w·x > θ), quindi classe 1, sotto, quindi classe 0. Il perceptron impara w e θ tali che gli esempi positivi/negativi siano separati.",
    '211': "L'encoder originale e' uno stack di 6 strati identici; ogni strato ha due sottostrati (multi-head self-attention + Feed-Forward Network) avvolti da residual connection e normalizzazione.",
    '212': "Il decoder ha tre sottostrati: self-attention mascherata, attention sull'output dell'encoder e FFN (l'encoder ne ha solo due).",
    '213': "Il mascheramento assicura che la predizione alla posizione i usi solo le posizioni precedenti, mai quelle future: il decoder genera la sequenza un token alla volta.",
    '214': "La residual connection somma l'input del sottostrato al suo output (poi si normalizza); per questo ogni sottostrato produce vettori della stessa dimensione.",
    '215': "Un language model assegna una probabilita' a qualsiasi sequenza di token presi da un vocabolario: e' una distribuzione di probabilita' sulle sequenze.",
    '216': "Per la regola della catena P(X1..Xn) = prodotto su k di P(Xk | X1:k-1): ogni token e' condizionato a tutti i precedenti.",
    '217': "Con l'assunzione di Markov la storia viene approssimata alle ultime poche parole (un bigramma usa solo la parola precedente), rendendo il calcolo trattabile.",
    '218': "One-hot rappresenta ogni parola con un vettore lungo quanto il vocabolario (un 1 e tanti 0): occupa molto spazio e non cattura alcuna relazione di significato tra termini.",
    '219': "'Un termine e' caratterizzato dalla sua compagnia': se due parole compaiono in contesti simili, hanno significato simile. E' l'idea che porta agli spazi vettoriali e agli embeddings.",
    '220': "A differenza del one-hot, gli embeddings sono corti (d tra 50 e 1000) e densi: catturano la semantica distribuzionale in poche dimensioni.",
    '221': "Un termine presente in pochi documenti ha alto IDF e aiuta a distinguerli; i termini presenti ovunque (stop words) non sono informativi. Lo schema tf-idf combina frequenza e IDF.",
    '222': "Prima il pre-training fa imparare la lingua, poi il fine-tuning aggiunge la capacita' di svolgere un compito, l'allineamento raffina il comportamento e infine ci sono le valutazioni.",
    '224': "Gli appunti notano esplicitamente che i sistemi artificiali mancano di grounding, cioe' di un ancoraggio percettivo, causale-informativo (affordance) e normativo-sociale al mondo reale.",
    '225': "Dato il proprio Markov blanket - genitori, discendenti e genitori dei discendenti - un nodo e' condizionalmente indipendente da tutti gli altri nodi della rete.",
    '226': "L'ingenuita' sta nell'assumere che gli n effetti siano indipendenti tra loro (data la causa): semplifica i conti ma nei casi reali spesso non e' vero.",
    '227': "La semantica globale riscrive la congiunta completa come prodotto delle condizionali locali P(Xi | parents(Xi)): la topologia della rete definisce implicitamente l'intera distribuzione.",
    '229': "La probabilita' a priori si assegna in assenza di prove; quella a posteriori (condizionata) tiene conto delle osservazioni gia' fatte.",
    '230': "Lo spazio campionario Omega = {w1,...,wk} raccoglie tutti i mondi possibili; gli eventi elementari sono mutuamente esclusivi (non si sovrappongono) ed esaustivi (li coprono tutti).",
}

MATCHING = {
    # (group_id, item_id) -> explanation
    ('1','1'): "In parole povere: Cane(Fuffi)⇒¬Gatto(Fuffi): tutti i simboli sono costanti (Fuffi). Niente variabili, quindi GROUND. È anche una formula FOL ma il termine più stretto è 'ground'.",
    ('1','2'): "In parole povere: ¬P ∨ P è vera in ogni interpretazione (legge del terzo escluso). TAUTOLOGIA.",
    ('1','3'): "In parole povere: Contiene variabili (x,y,z) e predicati con argomenti, quindi FORMULA FOL generica (non clausola perché ha sia ∨ sia ∧ a livello esterno, non solo disgiunzione di letterali).",
    ('1','4'): "In parole povere: A∨¬B∨C: disgiunzione di letterali (A, ¬B, C). Definizione esatta di CLAUSOLA.",
    ('1','5'): "In parole povere: ¬Caldo(x)∧Caldo(x): contiene variabile x, quindi è FOL. È anche una contraddizione, ma la tipologia richiesta tra le opzioni è FOL.",
    ('2','1'): "In parole povere: ¬Alfa(x)∨Beta(x)∨¬Gamma(x) ha un solo letterale positivo (Beta(x)). Una clausola di Horn ammette al più un letterale positivo, quindi questa è di Horn (anzi, definita). T.",
    ('2','2'): "In parole povere: Una clausola è disgiunzione di letterali. La formula data lo è chiaramente. T.",
    ('2','3'): "In parole povere: il modus ponens (generalizzato) attiva la regola (Alfa∧Gamma)⇒Beta solo quando tutti gli antecedenti sono fatti noti. Qui c'è Alfa(COST) ma manca Gamma(COST): la regola non si attiva. F.",
    ('2','4'): "In parole povere: Risoluzione opera su clausole. La formula è già clausola; con Alfa(COST) si può risolvere (¬Alfa(x) e Alfa(COST) unificano con θ={x/COST}). T.",
    ('2','5'): "In parole povere: il forward chaining attiva la regola (Alfa∧Gamma)⇒Beta solo quando tutti gli antecedenti sono fatti noti. Qui c'è Alfa(COST) ma manca Gamma(COST): la regola non si attiva e Beta non viene derivata. F.",
    ('3','1'): "In parole povere: BFS con costi unitari è ottima (trova soluzione minima per numero di azioni) e completa.",
    ('3','2'): "In parole povere: DFS può perdersi su cammini infiniti, quindi NON COMPLETA in generale (lo è solo su spazi finiti).",
    ('3','3'): "In parole povere: A* usa f(n)=g(n)+h(n) — la funzione di valutazione informata classica.",
    ('3','4'): "In parole povere: IDS combina memoria O(b·d) di DFS con completezza/ottimalità (per costi unitari) di BFS.",
    ('4','1'): "In parole povere: Scacchi: nessuna casualità, vedi tutta la scacchiera, quindi deterministico, informazione completa.",
    ('4','2'): "In parole povere: Backgammon: lancio dadi a ogni turno, quindi stocastico. Vedi tutto, quindi informazione completa.",
    ('4','3'): "In parole povere: Othello: senza randomness, scacchiera visibile, quindi deterministico, informazione completa.",
    ('4','4'): "In parole povere: Poker: mescolata casuale (stocastico) e carte avversarie nascoste (informazione incompleta).",
    ('5','1'): "In parole povere: Negli scacchi vedi sempre tutto lo stato (scacchiera), quindi completamente osservabile.",
    ('5','2'): "In parole povere: Nel poker non vedi le carte degli avversari, quindi parzialmente osservabile.",
    ('5','3'): "In parole povere: Classificatore di immagini: ogni immagine è episodio indipendente. La decisione su una non influenza le altre, quindi episodico.",
    ('5','4'): "In parole povere: Backgammon ha lancio dadi, quindi stocastico, non deterministico.",
    ('6','1'): "In parole povere: Schema standard CSP per N-regine: ogni regina è una variabile. Posizionarne una per colonna riduce vincoli ridondanti.",
    ('6','2'): "In parole povere: Dominio di ogni variabile è quando riga in cui posizionare la regina è quando {1..N}.",
    ('6','3'): "In parole povere: Vincoli binari: ogni coppia di regine non deve essere su stessa riga, colonna o diagonale.",
    ('6','4'): "In parole povere: Nei CSP la soluzione è l'ASSEGNAMENTO finale, non una sequenza di mosse (concetto di problem solving classico).",
    ('7','1'): "In parole povere: Spam detection con esempi etichettati spam/non-spam, quindi supervisionato classico.",
    ('7','2'): "In parole povere: Segmentazione clienti senza etichette, quindi clustering è quando non supervisionato.",
    ('7','3'): "In parole povere: LLM pre-training: predici la prossima parola dal contesto. Le 'etichette' sono i token del testo stesso, quindi auto/self-supervised.",
    ('8','1'): "In parole povere: Accuratezza è quando (TP+TN)/totale è quando predizioni corrette/totale. Definizione standard.",
    ('8','2'): "In parole povere: Convenzione: righe è quando vero (reale), colonne è quando predetto. La diagonale principale è quando predizioni corrette.",
    ('8','3'): "In parole povere: Alta accuratezza SUL TRAINING può essere overfitting. Solo l'accuratezza su TEST set non visto è indicativa di generalizzazione.",
    ('8','4'): "In parole povere: La confidence è una proprietà del classificatore (es. probabilità output di softmax), non derivabile dalla sola matrice di confusione.",
    ('8','5'): "In parole povere: Error rate è quando predizioni sbagliate/totale è quando 1 - accuratezza. Per definizione.",
    ('9','1'): "In parole povere: Negli alberi di decisione i nodi INTERNI testano un attributo (es. 'Età > 30?'). Le foglie predicono la classe.",
    ('9','2'): "In parole povere: Le foglie corrispondono alla classe predetta per le istanze che vi arrivano. Sono il 'leaf label'.",
    ('9','3'): "In parole povere: Si preferisce l'attributo con MAGGIOR information gain (riduce di più l'incertezza). Minor gain è quando peggior split. F!",
    ('9','4'): "In parole povere: Entropia(t) è quando -Σ p log p. Se tutte le istanze sono in una classe, p=1, log(1)=0, quindi entropia 0. Nodo puro è quando entropia nulla.",
    ('9','5'): "In parole povere: Prepruning ferma la crescita quando il guadagno è sotto soglia. Tecnica classica per controllare overfitting durante la costruzione.",
    ('10','1'): "In parole povere: Perceptron lineare è quando iperpiano singolo. XOR richiede frontiera non lineare (2 iperpiani). Famoso limite di Minsky-Papert.",
    ('10','2'): "In parole povere: Cybenko/Hornik 1989: MLP con 1 hidden layer e attivazioni non-lineari approssima qualunque funzione continua su un compatto.",
    ('10','3'): "In parole povere: σ'(x) è quando σ(x)(1-σ(x)). Mai identicamente nulla; tende a 0 agli estremi (vanishing gradient).",
    ('10','4'): "In parole povere: Backprop è quando -η ∇L: si va nella direzione opposta al gradiente. Stessa logica della discesa del gradiente.",
    ('10','5'): "In parole povere: η troppo grande: passi che 'saltano' il minimo, oscillazione, divergenza. Tipico debug di NN che esplode in NaN.",
    ('11','1'): "In parole povere: L'albero di expectiminimax ha 4 tipi di nodi: max (MAX gioca), min (MIN gioca), terminali (esito noto), casuali (cerchi, variabile aleatoria).",
    ('11','2'): "In parole povere: Sì: V(nodo_casuale) è quando Σ_r P(r) · V(figlio_r). È valore atteso pesato.",
    ('11','3'): "In parole povere: Quando non ci sono nodi casuali (n=1 evento), expectiminimax è quando minimax. Caso degenere.",
    ('11','4'): "In parole povere: No: la complessità è O(b^m · n^m), peggiore di O(b^m) per la presenza di n eventi casuali per nodo.",
    ('12','1'): "In parole povere: Fluente è quando predicato/relazione il cui valore può cambiare nel tempo (con esecuzione di azioni). Concetto chiave del situation calculus.",
    ('12','2'): "In parole povere: L'assioma di frame esprime persistenza: ciò che NON è effetto di un'azione mantiene il suo valore. Risolve (in parte) il frame problem.",
    ('12','3'): "In parole povere: PDDL è quando Planning Domain Definition Language. Standard per definire planning problems (stati, azioni, goal).",
    ('12','4'): "In parole povere: L'anomalia di Sussman MOSTRA il CONTRARIO: i sottogoal possono essere INTERDIPENDENTI, perseguirli linearmente può disfarne altri.",
    ('13','1'): "In parole povere: Disjoint(S) è quando le categorie in S non hanno istanze comuni. È esattamente l'enunciato.",
    ('13','2'): "Creare una 'Partizione' significa dividere un gruppo in categorie che non si accavallano mai (un elemento sta in una e una sola categoria) e che coprono tutti (nessuno resta fuori).",
    ('13','3'): "In parole povere: ExhaustiveDec(S,C) richiede che le categorie di S coprano tutte le istanze di C (no istanze di C fuori da S).",
    ('13','4'): "In parole povere: Disjoint NON implica Exhaustive: posso avere categorie disgiunte ma che non coprono tutto C (es. {Cane, Gatto} è disgiunto ma non copre tutti gli animali).",
    ('14','1'): "In parole povere: Pongo è un individuo specifico, Dalmata è la categoria, quindi Pongo è ISTANZA di Dalmata, quindi Member.",
    ('14','2'): "In parole povere: Dalmata e Cane sono entrambe CATEGORIE; Dalmata sottoclasse di Cane, quindi Is-a.",
    ('14','3'): "In parole povere: Tom è quando istanza, Bassotto è quando categoria, quindi Member.",
    ('14','4'): "In parole povere: Bassotto e Cane è quando categorie; Bassotto sottoclasse di Cane, quindi Is-a.",
    ('15','1'): "In parole povere: Manhattan domina 'tessere fuori posto': è sempre ≥ (perché conta passi reali, non solo presenza fuori posto). Ammissibile.",
    ('15','2'): "In parole povere: Tessere fuori posto è ammissibile (sottostima sempre) ma NON DOMINA Manhattan (è meno informativa). Ammissibile non dominante.",
    ('15','3'): "In parole povere: Costo medio × 10: nessuna garanzia di sottostima, può sovrastimare, quindi NON ammissibile.",
    ('16','1'): "In parole povere: ∀x (P(x)∨¬P(x)) è il terzo escluso quantificato, quindi vera in ogni modello, quindi VALIDA.",
    ('16','2'): "In parole povere: ∃x (P(x)∧¬P(x)) afferma esista qualcosa che sia P e non-P, quindi contraddizione, quindi INSODDISFACIBILE.",
    ('16','3'): "In parole povere: ∀x ∃y Ama(x,y) può essere vera in alcuni mondi (chi ama qualcuno) e falsa in altri (mondo senza amore), quindi soddisfacibile non valida.",
    ('17','1'): "In parole povere: Backtracking standard: assegna una variabile alla volta, torna indietro al primo conflitto.",
    ('17','2'): "In parole povere: Forward checking: dopo un assegnamento, controlla un vincolo alla volta ed elimina valori incompatibili dai domini futuri (consistenza locale rispetto al vincolo).",
    ('17','3'): "In parole povere: AC-3: verifica consistenza tra coppie di variabili (archi). Più potente di forward checking, propaga le restrizioni a coppie.",
    ('17','4'): "In parole povere: Backjumping: dal fallimento risale al nodo più recente CAUSA del conflitto (conflict-directed), saltando intermedi irrilevanti.",
    ('18','1'): "In parole povere: ¬A∨¬B∨C: un solo letterale positivo (C), quindi HORN. Equivalente alla regola A∧B→C.",
    ('18','2'): "In parole povere: A∨B∨¬C: due letterali positivi (A,B), quindi NON Horn.",
    ('18','3'): "In parole povere: ¬A: zero letterali positivi, quindi HORN (caso 'no head', vincolo di non).",
    ('18','4'): "In parole povere: P (singolo positivo): UN letterale positivo, zero negativi, quindi HORN (fact).",
    ('18','5'): "In parole povere: A∨B: due letterali positivi, quindi NON Horn.",
    ('20','1'): "In parole povere: n variabili booleane, quindi 2^n combinazioni, quindi 2^n - 1 parametri indipendenti (l'ultimo determinato dalla normalizzazione Σp è quando 1).",
    ('20','2'): "In parole povere: Definizione di indipendenza: P(X,Y) è quando P(X)P(Y). Equivalentemente P(X|Y)=P(X).",
    ('20','3'): "In parole povere: L'efficienza delle reti bayesiane viene proprio dallo sfruttare indipendenze condizionate: poche probabilità locali invece di una tabella esponenziale.",
    ('20','4'): "In parole povere: P(H|E) è quando P(E|H)P(H)/P(E). Inverte la direzione condizionale. È il teorema di Bayes.",
    ('21','1'): "In parole povere: Minimax assume entrambi i giocatori ottimi: MAX max, MIN min. Worst-case ragionamento.",
    ('21','2'): "In parole povere: α-β è una potatura SAFE: stesso risultato di minimax, solo più veloce. Non cambia mai il valore calcolato.",
    ('21','3'): "In parole povere: Con ordine perfetto delle mosse (best first), α-β ha complessità O(b^(m/2)) — radice del numero di nodi, quindi doppia profondità a parità di tempo.",
    ('21','4'): "In parole povere: α-β è formulato per giochi a 2 giocatori a somma zero. Per più giocatori serve max^n, NON è applicabile direttamente.",
    ('22','1'): "In parole povere: Transformer/LLM: meccanismo principale è SELF-ATTENTION (multi-head). Calcola pesi di rilevanza tra tutti i token della sequenza.",
    ('22','2'): "In parole povere: GAN: generatore vs discriminatore in gioco MINIMAX (zero-sum). G inganna, D distingue.",
    ('22','3'): "In parole povere: Diffusion: processo iterativo di DENOISING. Si apprende a invertire l'aggiunta progressiva di rumore.",
    ('22','4'): "In parole povere: CNN: convoluzioni 2D con filtri condivisi, pensate per immagini sfruttando località e invarianza traslazionale.",
    ('23','1'): "In parole povere: La risoluzione opera su clausole; si trasforma tutta la KB in CNF (clausole) prima di iniziare.",
    ('23','2'): "In parole povere: Refutazione è quando dimostra per ASSURDO: aggiungi ¬goal alla KB e cerchi la contraddizione.",
    ('23','3'): "In parole povere: Successo è quando derivare la clausola vuota □ (contraddizione). Conclude che la KB originale implica il goal.",
    ('23','4'): "In parole povere: FALSO: derivare □ non significa che la KB originale era contraddittoria, ma che KB ∪ {¬goal} lo è. La KB originale può essere coerente; il successo della refutazione prova KB ⊨ goal.",
    ('24','1'): "In parole povere: Termostato: percepisce T<20, quindi accende. Regola IF-THEN. Reattivo semplice.",
    ('24','2'): "In parole povere: Auto autonoma mantiene mappa interna (SLAM), quindi STATO interno, quindi basato su modello.",
    ('24','3'): "In parole povere: Pianificatore: ha goal esplicito, costruisce sequenza per raggiungerlo, quindi goal-driven.",
    ('24','4'): "In parole povere: Massimizza profitto è quando funzione di utilità, quindi utility-driven (più sofisticato di puramente goal-driven).",
    ('25','1'): "In parole povere: Pattern classico di overfitting: il modello memorizza il training ma non generalizza al test.",
    ('25','2'): "In parole povere: Prepruning ferma la crescita dell'albero quando guadagno < soglia, quindi impedisce di adattarsi troppo ai dati di training.",
    ('25','3'): "In parole povere: FALSO: più parametri non implica migliore. Spesso porta a overfitting. Rasoio di Occam: preferisci modelli semplici.",
    ('25','4'): "In parole povere: Occam: a parità di prestazioni, modello più semplice è da preferire (interpretabilità, robustezza, generalizzazione).",
    ('26','1'): "In parole povere: {P,Q} e {¬P,R}: P e ¬P unificano direttamente. Risolvente: {Q,R}. T.",
    ('26','2'): "In parole povere: {P} e {Q,R}: nessun letterale opposto. Risoluzione NON applicabile. F.",
    ('26','3'): "In parole povere: P(a) e ¬P(x) unificano con θ={x/a}. Risolvente: clausola vuota. Risoluzione FOL con lifting. T.",
    ('26','4'): "In parole povere: P(a) e ¬P(b): a, b costanti distinte, NON unificabili. Risoluzione non applicabile. F.",
    ('27','1'): "Una tassonomia e' l'organizzazione gerarchica di categorie collegate da relazioni is-a.",
    ('27','2'): "Bunch-of indica un oggetto composto da parti senza specificare le relazioni fra di esse.",
    ('27','3'): "Un'ontologia (rete semantica) e' l'insieme dei concetti di un dominio e delle loro relazioni, piu' generale di una tassonomia.",
    ('27','4'): "Part-of indica che un oggetto e' parte di un altro ed e' transitiva: Part-of(X,Y) and Part-of(Y,Z) => Part-of(X,Z).",
    ('28','1'): "In parole povere: BFS: coda FIFO, quindi first in, first out. I primi nodi inseriti (più superficiali) vengono espansi prima.",
    ('28','2'): "In parole povere: DFS: pila LIFO, quindi last in, first out. Gli ultimi inseriti (più profondi) vengono espansi per primi.",
    ('28','3'): "In parole povere: Uniform-cost: coda con priorità su costo g(n). Si espande sempre il più 'economico'.",
    ('28','4'): "In parole povere: IDS: lancia DLS con limite di profondità incrementale 0,1,2,... Combina memoria DFS con completezza BFS.",
    ('29','1'): "In parole povere: Sigmoide σ(x) è quando 1/(1+e^(-x)): output in (0,1), derivabile ovunque. Storica per output binari.",
    ('29','2'): "In parole povere: Tanh: tanh(x) ∈ (-1,1), derivabile. Simmetrica intorno a 0, gradiente migliore di sigmoide negli strati profondi.",
    ('29','3'): "In parole povere: ReLU: max(0,x). Lineare a tratti, in [0,+∞). Computazionalmente economica, evita vanishing gradient per x>0. Non differenziabile in 0 (ma trattata operativamente).",
    ('29','4'): "In parole povere: Gradino classico del perceptron originale: H(x) è quando 1 se x>0 else 0. NON differenziabile in 0 (salto). Per questo non usabile con backprop.",
    ('30','1'): "In parole povere: A∨¬A: terzo escluso. Sempre vero. T.",
    ('30','2'): "In parole povere: A∧¬A: contraddizione. Mai vera. NON soddisfacibile, quindi F.",
    ('30','3'): "In parole povere: A→B equivale a ¬A∨B per definizione di relazione logica di causa-effetto. T.",
    ('30','4'): "Se una teoria implica matematicamente una verità, provare a mettere insieme la teoria con il CONTRARIO di quella verità crea un cortocircuito logico (un'impossibilità).",
    ('31','1'): "Solo il decoder usa la self-attention mascherata, per non guardare i token futuri.",
    ('31','2'): "E' il sottostrato che collega decoder ed encoder: presente solo nel decoder.",
    ('31','3'): "Sia l'encoder sia il decoder hanno una FFN come ultimo sottostrato.",
    ('31','4'): "Residual + normalizzazione avvolgono ogni sottostrato in entrambi i blocchi.",
    ('31','5'): "L'encoder usa self-attention multi-head senza mascheramento (vede tutta la sequenza in input).",
    ('32','1'): "Ontologie equivalenti: stesso contenuto, linguaggio diverso.",
    ('32','2'): "O6 estende O7: contiene tutto cio' che c'e' in O7 e qualcosa in piu'.",
    ('32','3'): "Strongly-translatable: traduzione perfetta, niente perdite ne' inconsistenze.",
    ('32','4'): "Weakly-translatable: si traduce, ma qualcosa va perso.",
    ('33','1'): "Bias di copertura: errore nella fase di raccolta dei dati.",
    ('33','2'): "Bias di conferma in annotazione: l'etichettatore vede cio' che si aspetta.",
    ('33','3'): "Errore in addestramento: si stereotipano gli individui di un gruppo a cui non si appartiene.",
    ('33','4'): "Bias d'uso: si tende a fidarsi piu' dell'output automatico che di quello umano.",
}

def add_col(in_path, mapping):
    with open(in_path) as f:
        rows = list(csv.reader(f))
    header = rows[0]
    # Idempotente: se la colonna esiste già la sovrascriviamo, non la duplichiamo.
    if 'explanation' in header:
        idx = header.index('explanation')
    else:
        header.append('explanation')
        idx = len(header) - 1
    out = [header]
    for r in rows[1:]:
        key = r[0] if in_path.endswith('mcq.csv') else (r[0], r[1])
        expl = mapping.get(key, '(spiegazione non disponibile)')
        if idx < len(r):
            r[idx] = expl
        else:
            r = r + [''] * (idx - len(r)) + [expl]
        out.append(r)
    with open(in_path, 'w', newline='') as f:
        w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        w.writerows(out)
    return len(out) - 1

n_mcq = add_col('mcq.csv', MCQ)
n_mt = add_col('matching.csv', MATCHING)
print(f"mcq: {n_mcq} righe annotate")
print(f"matching: {n_mt} righe annotate")
# Find any missing
import csv as c2
with open('mcq.csv') as f:
    rows = list(c2.reader(f))
missing = [r[0] for r in rows[1:] if r[-1] == '(spiegazione non disponibile)']
print(f"MCQ senza spiegazione: {len(missing)} {missing}")
with open('matching.csv') as f:
    rows = list(c2.reader(f))
missing = [(r[0],r[1]) for r in rows[1:] if r[-1] == '(spiegazione non disponibile)']
print(f"Matching senza spiegazione: {len(missing)} {missing[:10]}")
