/* SISINT Made Easy — grafo dei concetti (estratto dagli appunti manoscritti).
   Nodo: {id, label, cat, blurb}.  Arco: {s, t, type} con type = prereq|isa|rel.
   'prereq' = s è prerequisito di t (dà la direzione ai layout DAG/MLP/albero).
   'isa'    = t è un tipo/sottocaso di s (tassonomia).
   'rel'    = collegamento generico (correlato/contrapposto). */

const CATS = {
  AG:   { label: 'Agenti',                color: '#3b82f6' },
  SE:   { label: 'Ricerca',               color: '#06b6d4' },
  CSP:  { label: 'CSP',                    color: '#14b8a6' },
  GA:   { label: 'Giochi',                color: '#f59e0b' },
  PL:   { label: 'Logica proposizionale', color: '#8b5cf6' },
  FOL:  { label: 'Logica del 1° ordine',  color: '#a855f7' },
  KR:   { label: 'Ontologie / KR',        color: '#ec4899' },
  ML:   { label: 'Apprendimento',         color: '#10b981' },
  NN:   { label: 'Reti neurali',          color: '#ef4444' },
  GEN:  { label: 'IA generativa',         color: '#f97316' },
  NLP:  { label: 'Transformer / LLM',     color: '#db2777' },
  PR:   { label: 'Probabilità / Bayes',   color: '#eab308' },
  PLAN: { label: 'Planning',              color: '#22c55e' }
};

const NODES = [
  // ===== AG — Agenti =====
  { id:'agente', cat:'AG', label:'Agente', blurb:'Entità che percepisce l\'ambiente con i sensori e agisce con gli attuatori. RAZIONALE = sceglie l\'azione che massimizza l\'utilità attesa date le sue conoscenze; AUTONOMO = riceve compiti ad alto livello e ragiona da solo su come risolverli (diverso dall\'automazione passo-passo).' },
  { id:'sensori_attuatori', cat:'AG', label:'Sensori e attuatori', blurb:'I sensori sono gli "occhi" (input dall\'ambiente), gli attuatori sono le "mani" (azioni sull\'ambiente). Sono l\'interfaccia tra agente e mondo.' },
  { id:'ambiente', cat:'AG', label:'Ambiente', blurb:'Classificato per proprietà: osservabile/parzialmente osservabile, deterministico/stocastico, noto/non noto, episodico/sequenziale. Da queste proprietà dipende il tipo di agente adatto.' },
  { id:'reattivo_semplice', cat:'AG', label:'Agente reattivo semplice', blurb:'Regole condizione→azione, nessuno stato interno. Ha senso solo in ambienti COMPLETAMENTE osservabili (es. termostato). Approccio basato su regole / albero di decisione semplice.' },
  { id:'basato_modello', cat:'AG', label:'Agente basato su modello', blurb:'Mantiene uno stato interno che traccia le parti del mondo non osservate (es. auto con mappa interna). Adatto agli ambienti parzialmente osservabili; spesso usa un approccio probabilistico (rete bayesiana).' },
  { id:'goal_driven', cat:'AG', label:'Agente goal-driven', blurb:'Sceglie le azioni per raggiungere un OBIETTIVO. Usa ricerca e pianificazione (albero delle azioni future). Es. navigatore GPS, automated planning.' },
  { id:'utility_driven', cat:'AG', label:'Agente utility-driven', blurb:'Massimizza una funzione di UTILITÀ: serve quando ci sono obiettivi in conflitto o gradi di soddisfazione. Approccio decisionale/ottimizzazione (es. bot di trading finanziario).' },
  { id:'approccio_dich_proc', cat:'AG', label:'Dichiarativo vs procedurale', blurb:'Approccio DICHIARATIVO = descrivo COSA voglio (la conoscenza); PROCEDURALE = descrivo COME farlo (la procedura).' },
  { id:'agente_apprende', cat:'AG', label:'Agente che apprende', blurb:'Quattro componenti: elemento esecutivo (agisce), elemento di apprendimento (migliora), modulo critico (valuta le prestazioni), generatore di problemi (propone esperienze nuove da provare).' },

  // ===== SE — Ricerca =====
  { id:'problema_ricerca', cat:'SE', label:'Problema di ricerca', blurb:'Definito da: stato iniziale, azioni/funzione successore, modello di transizione, test obiettivo e costo di cammino. Trappola: l\'euristica NON fa parte della definizione del problema.' },
  { id:'ricerca_cieca', cat:'SE', label:'Ricerca cieca (blind)', blurb:'Esplora usando solo la definizione del problema, senza stimare la distanza dal goal. Lavora su spazio degli stati, azioni possibili, modello di transizione e test obiettivo.' },
  { id:'tree_vs_graph', cat:'SE', label:'Tree vs Graph search', blurb:'La ricerca su ALBERO può riespandere stati già visti; la ricerca su GRAFO tiene una lista degli stati esplorati ed evita i duplicati.' },
  { id:'bfs', cat:'SE', label:'BFS', blurb:'Frontiera FIFO (coda): esplora prima i nodi più vicini alla radice. Completa; ottima se i costi sono unitari. Costosa in memoria.' },
  { id:'dfs', cat:'SE', label:'DFS', blurb:'Frontiera LIFO (pila): scende in profondità prima di tornare indietro. Memoria lineare O(b·m) — è il suo vantaggio — ma non è ottima.' },
  { id:'ids', cat:'SE', label:'IDS (iterative deepening)', blurb:'DFS ripetuta con limite di profondità crescente. Unisce la memoria lineare della DFS alla completezza/ottimalità (costi unitari) della BFS.' },
  { id:'ucs', cat:'SE', label:'UCS (costo uniforme)', blurb:'Come la BFS ma espande sempre il nodo con costo accumulato g(n) minimo. Ottima con costi di arco qualsiasi non negativi.' },
  { id:'ricerca_informata', cat:'SE', label:'Ricerca informata', blurb:'Usa in più un\'euristica h(n) che stima il costo dal nodo al goal, per esplorare in modo più mirato.' },
  { id:'euristica_h', cat:'SE', label:'Euristica h(n)', blurb:'Stima del costo residuo dal nodo n al goal. Non fa parte della definizione del problema: è uno strumento della ricerca informata.' },
  { id:'greedy', cat:'SE', label:'Greedy best-first', blurb:'Sceglie il nodo con h(n) minima (solo l\'euristica, ignora il costo già speso). Veloce ma non ottima né completa.' },
  { id:'a_star', cat:'SE', label:'A*', blurb:'Espande il nodo con f(n)=g(n)+h(n) minimo (costo speso + stima al goal). Ottima e completa se h è ammissibile (su grafo: consistente).' },
  { id:'ammissibile', cat:'SE', label:'Euristica ammissibile', blurb:'Non sovrastima MAI il costo reale per arrivare al goal. Garantisce l\'ottimalità di A* su alberi.' },
  { id:'consistente', cat:'SE', label:'Euristica consistente', blurb:'Rispetta la disuguaglianza triangolare: h(n) ≤ costo(n,n\') + h(n\'). La consistenza implica l\'ammissibilità e garantisce A* ottima su grafo.' },
  { id:'dominanza', cat:'SE', label:'Dominanza', blurb:'h2 domina h1 se h2(n) ≥ h1(n) per ogni n (restando ammissibile): è più informata e fa espandere meno nodi.' },

  // ===== CSP =====
  { id:'csp', cat:'CSP', label:'CSP', blurb:'Constraint Satisfaction Problem: definito da Variabili, Domini e Vincoli. È un caso particolare di problema di ricerca con struttura sugli stati.' },
  { id:'soluzione_csp', cat:'CSP', label:'Soluzione (CSP)', blurb:'Assegnamento COMPLETO (tutte le variabili assegnate) e CONSISTENTE (nessun vincolo violato).' },
  { id:'backtracking', cat:'CSP', label:'Backtracking', blurb:'Assegna una variabile alla volta; in caso di conflitto torna all\'assegnamento più recente e prova un altro valore.' },
  { id:'backjumping', cat:'CSP', label:'Backjumping', blurb:'Invece di tornare all\'ultima variabile, salta direttamente alla variabile più recente responsabile del conflitto (evita backtracking inutili).' },
  { id:'forward_checking', cat:'CSP', label:'Forward checking', blurb:'Dopo ogni assegnamento elimina dai domini delle variabili vicine i valori diventati incoerenti.' },
  { id:'propagazione', cat:'CSP', label:'Propagazione dei vincoli', blurb:'Sistema che "guarda avanti": propaga le conseguenze degli assegnamenti riducendo i domini prima di proseguire.' },
  { id:'arc_consistency', cat:'CSP', label:'Arc consistency', blurb:'Un arco X→Y è consistente se per ogni valore di X esiste almeno un valore compatibile in Y.' },
  { id:'ac3', cat:'CSP', label:'AC-3', blurb:'Algoritmo che impone l\'arc-consistency lavorando a coppie (2-consistency), continuando finché i domini non si stabilizzano. Riduce lo spazio ma non garantisce da solo la soluzione.' },
  { id:'k_consistency', cat:'CSP', label:'k-consistency', blurb:'Ogni assegnamento consistente di k-1 variabili è estendibile a una k-esima. Più alto è k, più conflitti vengono individuati in anticipo.' },
  { id:'esempio_csp', cat:'CSP', label:'Esempi: mappa / N-regine', blurb:'Colorazione della mappa (regioni adiacenti di colore diverso) e N-regine (nessuna regina si attacca) sono CSP classici risolti con backtracking + propagazione.' },

  // ===== GA — Giochi =====
  { id:'giochi', cat:'GA', label:'Giochi', blurb:'Classificati per: deterministico vs stocastico, osservabilità completa vs incompleta, somma zero (i giocatori hanno utilità opposte). Ricerca con avversario.' },
  { id:'funzione_valutazione', cat:'GA', label:'Funzione di valutazione', blurb:'Stima l\'utilità di uno stato non terminale quando l\'albero è troppo grande per arrivare alle foglie.' },
  { id:'minimax', cat:'GA', label:'Minimax', blurb:'Per giochi deterministici a 2 giocatori a somma zero: MAX massimizza, MIN minimizza, assumendo l\'avversario ottimo.' },
  { id:'alfa_beta', cat:'GA', label:'Potatura alfa-beta', blurb:'α = miglior valore garantito per MAX, β = miglior valore per MIN. Dà lo stesso risultato di minimax ma esplora molti meno nodi tagliando i rami inutili.' },
  { id:'expectiminimax', cat:'GA', label:'Expectiminimax', blurb:'Estende il minimax ai giochi stocastici aggiungendo nodi "caso": serve conoscere la distribuzione di probabilità degli eventi casuali.' },

  // ===== PL — Logica proposizionale =====
  { id:'logica_prop', cat:'PL', label:'Logica proposizionale', blurb:'Le variabili sono "fatti" veri/falsi, combinati con connettivi logici (¬, ∧, ∨, →). Base del ragionamento simbolico.' },
  { id:'modello', cat:'PL', label:'Modello', blurb:'Un assegnamento di valori di verità a ogni simbolo proposizionale che rende vera una formula.' },
  { id:'tautologia', cat:'PL', label:'Tautologia', blurb:'Formula vera in OGNI interpretazione (sempre vera). Legata al concetto di validità.' },
  { id:'soddisfacibile', cat:'PL', label:'Soddisfacibile', blurb:'Formula vera in ALMENO una interpretazione. Concetto chiave: una conseguenza logica è risolvibile riducendola a un problema di soddisfacibilità.' },
  { id:'contraddizione', cat:'PL', label:'Contraddizione', blurb:'Formula vera in NESSUNA interpretazione (sempre falsa). È l\'opposto della tautologia.' },
  { id:'entailment', cat:'PL', label:'Entailment (⊨)', blurb:'Conseguenza logica: KB ⊨ α se α è vera in tutti i modelli della KB. Si verifica controllando che KB ∧ ¬α sia insoddisfacibile.' },
  { id:'correttezza', cat:'PL', label:'Correttezza (soundness)', blurb:'Un sistema di inferenza è corretto se deriva SOLO conseguenze logiche: KB ⊢ α ⟹ KB ⊨ α.' },
  { id:'completezza', cat:'PL', label:'Completezza', blurb:'Un sistema è completo se deriva TUTTE le conseguenze logiche: KB ⊨ α ⟹ KB ⊢ α.' },
  { id:'kb_consistente', cat:'PL', label:'KB consistente', blurb:'Una base di conoscenza è consistente se ha almeno un modello (esiste un\'interpretazione che la rende vera).' },
  { id:'formula_atomica', cat:'PL', label:'Formula atomica', blurb:'La proposizione più semplice, una singola variabile (es. P) o un predicato applicato in FOL (es. Ama(Giovanni,Maria)).' },
  { id:'letterale', cat:'PL', label:'Letterale', blurb:'Una formula atomica o la sua negazione (es. P oppure ¬P).' },
  { id:'clausola', cat:'PL', label:'Clausola', blurb:'Disgiunzione di letterali (OR), es. (A ∨ ¬B ∨ C). Mattone della risoluzione.' },
  { id:'clausola_horn', cat:'PL', label:'Clausola di Horn', blurb:'Clausola con al massimo UN letterale positivo. Permette inferenza efficiente (forward/backward chaining).' },
  { id:'cnf', cat:'PL', label:'CNF (forma normale congiuntiva)', blurb:'AND di clausole (OR di letterali). Si ottiene eliminando le → (X→Y ≡ ¬X∨Y) e applicando De Morgan. Es: ¬(A→B)∨C ⟹ (A∨C)∧(¬B∨C).' },
  { id:'modus_ponens', cat:'PL', label:'Modus ponens', blurb:'Regola di inferenza: da R→Q e R si deduce Q. Calcola le conseguenze su clausole (positive).' },
  { id:'forward_chaining', cat:'PL', label:'Forward chaining', blurb:'Data-driven: parte dai fatti noti e applica le regole in avanti fino a derivare il goal. Es. da A→C, B→D, C∧D→E…' },
  { id:'backward_chaining', cat:'PL', label:'Backward chaining', blurb:'Goal-driven: parte dal goal e cerca a ritroso le regole/fatti che lo dimostrano.' },
  { id:'risoluzione', cat:'PL', label:'Risoluzione', blurb:'Regola di inferenza completa per refutazione: da due clausole con un letterale opposto (es. A∨B e ¬A∨C) deriva il "resolvente" B∨C.' },
  { id:'refutazione', cat:'PL', label:'Dimostrazione per refutazione', blurb:'Per dimostrare KB ⊨ G si aggiunge ¬G alla KB e si cerca una contraddizione: se la KB ∧ ¬G è insoddisfacibile, allora G è vera.' },

  // ===== FOL — Logica del primo ordine =====
  { id:'fol', cat:'FOL', label:'FOL (logica del 1° ordine)', blurb:'Estende la logica proposizionale con oggetti, relazioni, funzioni e quantificatori: permette di parlare di "tutti" e "esiste".' },
  { id:'quantificatori', cat:'FOL', label:'Quantificatori', blurb:'∀ (per ogni) si usa tipicamente con → ; ∃ (esiste) si usa tipicamente con ∧.' },
  { id:'costanti_variabili', cat:'FOL', label:'Costanti e variabili', blurb:'Le costanti denotano oggetti specifici (Socrate); le variabili (x, y) denotano oggetti generici da quantificare.' },
  { id:'predicati', cat:'FOL', label:'Predicati', blurb:'Esprimono proprietà — Uomo(Socrate) — o relazioni — Ama(Giovanni, Aida). Restituiscono vero/falso.' },
  { id:'funzioni', cat:'FOL', label:'Funzioni', blurb:'Mappano oggetti in oggetti (non in valori di verità): es. Madre(Giovanni) denota una persona.' },
  { id:'ground', cat:'FOL', label:'Ground', blurb:'Termine o formula SENZA variabili, contenente solo costanti.' },
  { id:'lifting', cat:'FOL', label:'Lifting', blurb:'Solleva l\'inferenza proposizionale a FOL ragionando direttamente con le variabili, senza istanziare tutto in ground.' },
  { id:'unificazione', cat:'FOL', label:'Unificazione', blurb:'Trova una sostituzione che rende identiche due formule (es. Conosce(x,y) e Conosce(Giovanni,Maria)). È il motore del lifting.' },
  { id:'mgu', cat:'FOL', label:'MGU (most general unifier)', blurb:'L\'unificatore più generale: la sostituzione minima che unifica due espressioni senza vincolare più del necessario.' },
  { id:'skolemizzazione', cat:'FOL', label:'Skolemizzazione', blurb:'Elimina i quantificatori ∃ introducendo una costante (o funzione) di Skolem che rappresenta l\'oggetto la cui esistenza è asserita.' },
  { id:'inferenza', cat:'FOL', label:'Inferenza', blurb:'Ragionamento/deduzione di nuove conclusioni a partire dai dati e dalla base di conoscenza.' },

  // ===== KR — Ontologie / Knowledge Representation =====
  { id:'tassonomia', cat:'KR', label:'Tassonomia', blurb:'Gerarchia di relazioni IS-A tra categorie, con ereditarietà: una sottoclasse eredita le proprietà della superclasse.' },
  { id:'ontologia', cat:'KR', label:'Ontologia', blurb:'Insieme di concetti e relazioni di un dominio — NON solo gerarchia: include relazioni di ogni tipo (part-of, attributi, ecc.).' },
  { id:'isa_vs_member', cat:'KR', label:'IS-A vs MEMBER', blurb:'IS-A collega due CATEGORIE (Cane is-a Animale); MEMBER collega un INDIVIDUO a una categoria (Fido member-of Cane).' },
  { id:'disjoint', cat:'KR', label:'Disjoint', blurb:'Un insieme di sottoclassi è disjoint se sono a coppie disgiunte (nessuna istanza appartiene a due di esse).' },
  { id:'decomposizione_esaustiva', cat:'KR', label:'Decomposizione esaustiva', blurb:'Ogni istanza della classe C appartiene ad almeno una delle sottoclassi S (le sottoclassi coprono tutta C).' },
  { id:'partition', cat:'KR', label:'Partition', blurb:'Disjoint + decomposizione esaustiva: le sottoclassi sono disgiunte E coprono completamente la classe.' },
  { id:'semantic_web', cat:'KR', label:'Semantic Web', blurb:'Estensione del web in cui i dati hanno un significato leggibile dalle macchine; applicazione concreta delle tecniche di KR/AI.' },
  { id:'rdf', cat:'KR', label:'RDF', blurb:'Resource Description Framework: rappresenta la conoscenza in triple soggetto → predicato → oggetto. Standard di base del semantic web.' },
  { id:'owl', cat:'KR', label:'OWL', blurb:'Web Ontology Language: RDF arricchito con costrutti logici che permettono l\'inferenza automatica.' },
  { id:'part_of', cat:'KR', label:'Part-of', blurb:'Relazione parte-tutto: un oggetto è composto dall\'insieme delle sue parti (con relazioni strutturali).' },
  { id:'bunch_of', cat:'KR', label:'Bunch-of', blurb:'Aggregato di parti SENZA relazioni strutturali tra loro: conta solo l\'insieme delle parti.' },
  { id:'assiomatizzazione', cat:'KR', label:'Assiomatizzazione', blurb:'Gli assiomi sono le "regole" del linguaggio dell\'ontologia: definiscono cosa è vero per costruzione.' },
  { id:'allineamento_ontologie', cat:'KR', label:'Allineamento di ontologie', blurb:'Mettere in corrispondenza ontologie diverse. Equivalenti = condividono linguaggio e assiomi; estensioni = una preserva l\'altra; translatable forte/debole (con possibile perdita di informazione).' },

  // ===== ML — Apprendimento =====
  { id:'apprendimento', cat:'ML', label:'Apprendimento automatico', blurb:'Costruire modelli che migliorano dall\'esperienza/dati invece di essere programmati con regole esplicite.' },
  { id:'supervisionato', cat:'ML', label:'Supervisionato', blurb:'Impara da esempi ETICHETTATI (input → output noto). Tipici: classificazione e regressione.' },
  { id:'non_supervisionato', cat:'ML', label:'Non supervisionato', blurb:'Nessuna etichetta: il modello scopre struttura nei dati, es. il clustering.' },
  { id:'auto_supervisionato', cat:'ML', label:'Auto-supervisionato', blurb:'Ricava il "supervisore" dagli stessi dati (es. predire una parola mascherata): a metà tra supervisionato e non supervisionato.' },
  { id:'classificazione', cat:'ML', label:'Classificazione', blurb:'Imparare da esempi ad assegnare ogni istanza a una CLASSE discreta.' },
  { id:'attributi', cat:'ML', label:'Attributi', blurb:'Le caratteristiche di un\'istanza: binari, nominali, ordinali, continui (questi ultimi gestiti con soglie negli alberi).' },
  { id:'albero_decisione', cat:'ML', label:'Albero di decisione', blurb:'Modello a test sugli attributi: ogni nodo fa uno split (scelto per guadagno), le foglie sono le classi.' },
  { id:'algoritmo_hunt', cat:'ML', label:'Algoritmo di Hunt', blurb:'Costruzione top-down e ricorsiva dell\'albero: se un nodo è "puro" diventa foglia, altrimenti si sceglie l\'attributo migliore e si partiziona.' },
  { id:'information_gain', cat:'ML', label:'Information gain', blurb:'Riduzione di entropia data da uno split: entropia del padre − media pesata dell\'entropia dei figli. Si sceglie lo split col gain massimo.' },
  { id:'gini', cat:'ML', label:'Indice di Gini', blurb:'Misura alternativa di impurità: 1 − Σ (frequenze)². Più basso = nodo più puro.' },
  { id:'entropia', cat:'ML', label:'Entropia / impurità', blurb:'Misura l\'incertezza/impurità di un nodo: massima quando le classi sono mescolate, nulla quando il nodo è puro.' },
  { id:'pruning', cat:'ML', label:'Pruning', blurb:'PRE-pruning ferma in anticipo la crescita dell\'albero; POST-pruning lo pota dopo (più costoso ma più efficace). Serve a contrastare l\'overfitting.' },
  { id:'overfitting', cat:'ML', label:'Overfitting', blurb:'Modello troppo aderente ai dati di training: perde capacità di generalizzazione, errore basso sul training ma alto sul test.' },
  { id:'underfitting', cat:'ML', label:'Underfitting', blurb:'Modello troppo semplice per i dati: errore alto sia sul training sia sul test.' },
  { id:'bias_modello', cat:'ML', label:'Bias (errore)', blurb:'Errore dovuto ad assunzioni troppo rigide del modello. Bias alto → underfitting.' },
  { id:'varianza', cat:'ML', label:'Varianza', blurb:'Sensibilità del modello alle fluttuazioni del training set. Varianza alta → overfitting (modello troppo complesso).' },
  { id:'rasoio_occam', cat:'ML', label:'Rasoio di Occam', blurb:'A parità di prestazioni, preferisci il modello più SEMPLICE: tende a generalizzare meglio.' },
  { id:'mdl', cat:'ML', label:'MDL (Minimum Description Length)', blurb:'Formalizza Occam: minimizza L(modello) + L(dati|modello), cioè la descrizione del modello più gli errori/eccezioni.' },
  { id:'rote_learning_knn', cat:'ML', label:'Rote learning / k-NN', blurb:'Memorizza le istanze e su una nuova cerca le più simili (k-NN), senza generalizzare. Voto a maggioranza → voto pesato (i vicini più vicini contano di più).' },
  { id:'matrice_costi', cat:'ML', label:'Matrice dei costi', blurb:'Assegna un costo a ogni tipo di errore (ogni cella): permette di pesare diversamente le predizioni sbagliate.' },
  { id:'matrice_confusione', cat:'ML', label:'Matrice di confusione', blurb:'Righe = classe reale, colonne = classe predetta; la diagonale sono le predizioni corrette.' },
  { id:'accuratezza', cat:'ML', label:'Accuratezza / error rate', blurb:'Accuratezza = corrette / totale; error rate = 1 − accuratezza.' },
  { id:'training_test_set', cat:'ML', label:'Training / Test set', blurb:'Training set (~70-80% dei dati) per addestrare; test set = dati MAI usati in addestramento, per valutare la generalizzazione.' },
  { id:'cross_validation', cat:'ML', label:'Cross-validation', blurb:'k-fold: ruota la partizione train/validation su k pieghe per stimare le prestazioni in modo più robusto.' },

  // ===== NN — Reti neurali =====
  { id:'perceptron', cat:'NN', label:'Perceptron', blurb:'Primo modello matematico di neurone: combina gli input con dei pesi e separa con una retta/iperpiano. Da solo traccia solo confini lineari.' },
  { id:'problema_xor', cat:'NN', label:'Problema dello XOR', blurb:'Lo XOR non è separabile con una singola retta/iperpiano: serve più di un percettrone.' },
  { id:'reti_neurali', cat:'NN', label:'Reti neurali', blurb:'Più percettroni collegati per risolvere problemi complessi non lineari (come lo XOR).' },
  { id:'mlp', cat:'NN', label:'MLP (multi-layer perceptron)', blurb:'Rete con più strati di percettroni (input, nascosti, output): può approssimare funzioni complesse.' },
  { id:'epoca', cat:'NN', label:'Epoca', blurb:'Un passaggio completo dell\'addestramento su tutto il training set (come leggere tutto il libro una volta).' },
  { id:'gradiente', cat:'NN', label:'Gradiente', blurb:'La "pendenza" dell\'errore rispetto ai pesi: indica la direzione in cui modificare i pesi per ridurre l\'errore.' },
  { id:'backpropagation', cat:'NN', label:'Backpropagation', blurb:'Dopo aver calcolato l\'errore in uscita, lo propaga all\'indietro strato per strato per aggiornare i pesi (usando il gradiente).' },
  { id:'cnn', cat:'NN', label:'CNN', blurb:'Reti convoluzionali: perfette per le immagini, sfruttano filtri locali che riconoscono pattern spaziali.' },
  { id:'rnn', cat:'NN', label:'RNN', blurb:'Reti ricorrenti: perfette per il testo/sequenze, mantengono uno stato che ricorda gli elementi precedenti.' },
  { id:'autoencoder', cat:'NN', label:'Autoencoder', blurb:'Rete con uno strato centrale stretto (pochi neuroni): comprime l\'input e poi lo ricostruisce. Usata anche per rilevare anomalie.' },

  // ===== GEN — IA generativa =====
  { id:'ia_generativa', cat:'GEN', label:'IA generativa', blurb:'Modelli che GENERANO nuovi contenuti. Architetture tipiche: Transformer/LLM, GAN, modelli di diffusione, CNN.' },
  { id:'gan', cat:'GEN', label:'GAN', blurb:'Due reti in competizione: il GENERATORE produce esempi falsi, il DISCRIMINATORE prova a distinguere veri/falsi. Si migliorano a vicenda finché i falsi non sono indistinguibili.' },
  { id:'addestramento_avversariale', cat:'GEN', label:'Addestramento avversariale', blurb:'Schema in cui due reti (es. generatore e discriminatore) si allenano una CONTRO l\'altra, spingendosi a migliorare.' },
  { id:'modelli_diffusione', cat:'GEN', label:'Modelli di diffusione', blurb:'Generano immagini partendo da rumore puro e applicando un denoising progressivo passo dopo passo.' },
  { id:'clustering', cat:'GEN', label:'Clustering', blurb:'Raggruppa istanze SIMILI senza etichette (apprendimento non supervisionato).' },
  { id:'k_means', cat:'GEN', label:'K-means', blurb:'k centroidi (k è un iperparametro): assegna ogni punto al centroide più vicino, poi ricalcola i centroidi, e si ripete fino a convergenza.' },

  // ===== NLP — Transformer / LLM =====
  { id:'language_model', cat:'NLP', label:'Language model', blurb:'Modello probabilistico (catena) che cerca di indovinare la parola successiva data la sequenza precedente.' },
  { id:'assunzione_markov', cat:'NLP', label:'Assunzione di Markov', blurb:'Per predire la prossima parola non si guarda tutto il passato, ma solo le ultime k parole.' },
  { id:'naive_bayes', cat:'NLP', label:'Naive Bayes', blurb:'Classificatore probabilistico veloce che assume (ingenuamente) l\'indipendenza condizionata di tutte le feature: irrealistico ma spesso efficace.' },
  { id:'one_hot', cat:'NLP', label:'One-hot encoding', blurb:'Trasforma le parole in numeri: ogni parola è un vettore con un solo 1. Semplice ma enorme e senza nozione di similarità.' },
  { id:'tf_idf', cat:'NLP', label:'TF-IDF', blurb:'Pesa le parole per quanto sono frequenti in un documento ma rare nel corpus: dà più peso alle parole caratterizzanti.' },
  { id:'embeddings', cat:'NLP', label:'Embeddings', blurb:'Rappresenta le parole come vettori densi in cui parole con significato simile finiscono VICINE nello spazio.' },
  { id:'transformer', cat:'NLP', label:'Transformer (GPT)', blurb:'Architettura che legge tutte le parole insieme e usa l\'attention: ogni parola "guarda" tutte le altre per capire il contesto.' },
  { id:'attention', cat:'NLP', label:'Attention', blurb:'Meccanismo per cui ogni parola pesa quanto le altre parole sono rilevanti per interpretarla.' },
  { id:'encoder_decoder', cat:'NLP', label:'Encoder / Decoder', blurb:'Encoder analizza/comprende l\'input; decoder genera l\'output. I modelli GPT sono decoder-only.' },
  { id:'masking', cat:'NLP', label:'Masking', blurb:'In addestramento nasconde le parole future così che il modello impari a predirle senza "barare" guardandole.' },
  { id:'residual_connections', cat:'NLP', label:'Residual connections', blurb:'Collegamenti che saltano gli strati per non perdere l\'informazione iniziale e facilitare l\'addestramento di reti profonde.' },
  { id:'grounding', cat:'NLP', label:'Grounding', blurb:'Collegare i simboli/parole al loro significato nel mondo reale: gli LLM "sanno parlare ma non significano" se manca il grounding.' },
  { id:'bias_dati', cat:'NLP', label:'Bias (nei dati)', blurb:'I pregiudizi presenti nei dati umani di addestramento vengono appresi e riprodotti dal modello.' },

  // ===== PR — Probabilità / Reti bayesiane =====
  { id:'probabilita_var', cat:'PR', label:'Probabilità e variabili aleatorie', blurb:'Una variabile aleatoria assegna esiti a uno spazio campionario (l\'universo dei casi possibili); la probabilità ne misura la frequenza/credenza.' },
  { id:'teorema_bayes', cat:'PR', label:'Teorema di Bayes', blurb:'Collega probabilità a priori e a posteriori: P(H|E) ∝ P(E|H)·P(H). Aggiorna la credenza iniziale alla luce dell\'evidenza.' },
  { id:'indipendenza_condizionata', cat:'PR', label:'Indipendenza condizionata', blurb:'Due variabili sono indipendenti DATA una condizione: conoscere la condizione rende i calcoli fattorizzabili (riduce i parametri).' },
  { id:'reti_bayesiane', cat:'PR', label:'Reti bayesiane', blurb:'Grafo a frecce aciclico (DAG) che codifica la semantica locale di Markov: ogni nodo dipende solo dai genitori. Compatta le distribuzioni con le CPT.' },
  { id:'cpt', cat:'PR', label:'CPT (tabella di prob. condizionata)', blurb:'Per ogni nodo della rete bayesiana elenca P(nodo | genitori): è il "parametro" locale del modello.' },

  // ===== PLAN — Planning =====
  { id:'planning', cat:'PLAN', label:'Planning', blurb:'Trovare una SEQUENZA di azioni che porta dallo stato iniziale a uno stato goal.' },
  { id:'pddl', cat:'PLAN', label:'PDDL', blurb:'Planning Domain Definition Language: descrive dominio e problema; ogni azione è definita da precondizioni ed effetti.' },
  { id:'situation_calculus', cat:'PLAN', label:'Situation calculus', blurb:'Rappresenta il mondo come "fotografie" (situazioni); la funzione Result(azione, situazione) produce la nuova situazione, partendo da S0.' },
  { id:'fluenti', cat:'PLAN', label:'Fluenti', blurb:'I fatti che CAMBIANO da una situazione all\'altra (a differenza di ciò che resta costante).' },
  { id:'assiomi_planning', cat:'PLAN', label:'Assiomi (possibilità/frame)', blurb:'Assiomi di possibilità: quando un\'azione è applicabile e i suoi effetti; assiomi di frame: ciò che NON cambia dopo l\'azione.' },
  { id:'frame_problem', cat:'PLAN', label:'Frame problem', blurb:'Il problema di esprimere che, dato un cambiamento, tutto il resto resta invariato. Soluzione: gli assiomi di stato-successore.' },
  { id:'anomalia_sussman', cat:'PLAN', label:'Anomalia di Sussman', blurb:'Caso in cui perseguire i sotto-goal in modo indipendente fa interferire un sotto-goal con l\'altro: mostra che il planning lineare ingenuo fallisce.' }
];

const EDGES = [
  // AG
  { s:'agente', t:'reattivo_semplice', type:'isa' },
  { s:'agente', t:'basato_modello', type:'isa' },
  { s:'agente', t:'goal_driven', type:'isa' },
  { s:'agente', t:'utility_driven', type:'isa' },
  { s:'agente', t:'agente_apprende', type:'isa' },
  { s:'agente', t:'sensori_attuatori', type:'rel' },
  { s:'agente', t:'ambiente', type:'rel' },
  { s:'agente', t:'approccio_dich_proc', type:'rel' },
  { s:'reattivo_semplice', t:'albero_decisione', type:'rel' },
  { s:'goal_driven', t:'problema_ricerca', type:'prereq' },
  { s:'goal_driven', t:'planning', type:'prereq' },
  { s:'basato_modello', t:'reti_bayesiane', type:'rel' },
  { s:'agente_apprende', t:'apprendimento', type:'rel' },

  // SE
  { s:'problema_ricerca', t:'ricerca_cieca', type:'prereq' },
  { s:'problema_ricerca', t:'ricerca_informata', type:'prereq' },
  { s:'problema_ricerca', t:'csp', type:'rel' },
  { s:'problema_ricerca', t:'giochi', type:'rel' },
  { s:'ricerca_cieca', t:'tree_vs_graph', type:'rel' },
  { s:'ricerca_cieca', t:'bfs', type:'isa' },
  { s:'ricerca_cieca', t:'dfs', type:'isa' },
  { s:'ricerca_cieca', t:'ids', type:'isa' },
  { s:'ricerca_cieca', t:'ucs', type:'isa' },
  { s:'bfs', t:'ucs', type:'rel' },
  { s:'dfs', t:'ids', type:'rel' },
  { s:'ricerca_informata', t:'euristica_h', type:'prereq' },
  { s:'ricerca_informata', t:'greedy', type:'isa' },
  { s:'ricerca_informata', t:'a_star', type:'isa' },
  { s:'euristica_h', t:'greedy', type:'prereq' },
  { s:'euristica_h', t:'a_star', type:'prereq' },
  { s:'euristica_h', t:'dominanza', type:'rel' },
  { s:'a_star', t:'ammissibile', type:'prereq' },
  { s:'a_star', t:'consistente', type:'prereq' },
  { s:'ammissibile', t:'consistente', type:'rel' },

  // CSP
  { s:'csp', t:'soluzione_csp', type:'prereq' },
  { s:'csp', t:'backtracking', type:'isa' },
  { s:'csp', t:'backjumping', type:'isa' },
  { s:'csp', t:'forward_checking', type:'isa' },
  { s:'csp', t:'propagazione', type:'prereq' },
  { s:'csp', t:'esempio_csp', type:'rel' },
  { s:'backtracking', t:'backjumping', type:'rel' },
  { s:'forward_checking', t:'propagazione', type:'rel' },
  { s:'propagazione', t:'arc_consistency', type:'prereq' },
  { s:'arc_consistency', t:'ac3', type:'prereq' },
  { s:'arc_consistency', t:'k_consistency', type:'rel' },

  // GA
  { s:'giochi', t:'funzione_valutazione', type:'prereq' },
  { s:'giochi', t:'minimax', type:'isa' },
  { s:'giochi', t:'expectiminimax', type:'isa' },
  { s:'minimax', t:'alfa_beta', type:'prereq' },
  { s:'minimax', t:'expectiminimax', type:'rel' },

  // PL
  { s:'logica_prop', t:'modello', type:'prereq' },
  { s:'modello', t:'tautologia', type:'prereq' },
  { s:'modello', t:'soddisfacibile', type:'prereq' },
  { s:'modello', t:'contraddizione', type:'prereq' },
  { s:'logica_prop', t:'entailment', type:'prereq' },
  { s:'entailment', t:'soddisfacibile', type:'rel' },
  { s:'entailment', t:'tautologia', type:'rel' },
  { s:'logica_prop', t:'correttezza', type:'rel' },
  { s:'logica_prop', t:'completezza', type:'rel' },
  { s:'correttezza', t:'completezza', type:'rel' },
  { s:'logica_prop', t:'kb_consistente', type:'rel' },
  { s:'logica_prop', t:'formula_atomica', type:'prereq' },
  { s:'formula_atomica', t:'letterale', type:'prereq' },
  { s:'letterale', t:'clausola', type:'prereq' },
  { s:'clausola', t:'clausola_horn', type:'isa' },
  { s:'clausola', t:'cnf', type:'prereq' },
  { s:'cnf', t:'risoluzione', type:'prereq' },
  { s:'risoluzione', t:'refutazione', type:'prereq' },
  { s:'entailment', t:'refutazione', type:'rel' },
  { s:'clausola_horn', t:'modus_ponens', type:'prereq' },
  { s:'modus_ponens', t:'forward_chaining', type:'rel' },
  { s:'entailment', t:'forward_chaining', type:'prereq' },
  { s:'entailment', t:'backward_chaining', type:'prereq' },
  { s:'forward_chaining', t:'backward_chaining', type:'rel' },

  // FOL
  { s:'logica_prop', t:'fol', type:'prereq' },
  { s:'fol', t:'quantificatori', type:'prereq' },
  { s:'fol', t:'costanti_variabili', type:'prereq' },
  { s:'fol', t:'predicati', type:'isa' },
  { s:'fol', t:'funzioni', type:'isa' },
  { s:'fol', t:'ground', type:'prereq' },
  { s:'fol', t:'inferenza', type:'rel' },
  { s:'inferenza', t:'entailment', type:'rel' },
  { s:'ground', t:'lifting', type:'prereq' },
  { s:'lifting', t:'unificazione', type:'prereq' },
  { s:'unificazione', t:'mgu', type:'prereq' },
  { s:'fol', t:'skolemizzazione', type:'prereq' },

  // KR
  { s:'ontologia', t:'tassonomia', type:'prereq' },
  { s:'tassonomia', t:'isa_vs_member', type:'rel' },
  { s:'tassonomia', t:'disjoint', type:'prereq' },
  { s:'disjoint', t:'partition', type:'prereq' },
  { s:'decomposizione_esaustiva', t:'partition', type:'prereq' },
  { s:'ontologia', t:'decomposizione_esaustiva', type:'rel' },
  { s:'ontologia', t:'semantic_web', type:'prereq' },
  { s:'semantic_web', t:'rdf', type:'prereq' },
  { s:'rdf', t:'owl', type:'prereq' },
  { s:'ontologia', t:'part_of', type:'rel' },
  { s:'part_of', t:'bunch_of', type:'rel' },
  { s:'ontologia', t:'assiomatizzazione', type:'prereq' },
  { s:'ontologia', t:'allineamento_ontologie', type:'prereq' },
  { s:'assiomatizzazione', t:'allineamento_ontologie', type:'rel' },
  { s:'fol', t:'ontologia', type:'rel' },

  // ML
  { s:'apprendimento', t:'supervisionato', type:'isa' },
  { s:'apprendimento', t:'non_supervisionato', type:'isa' },
  { s:'apprendimento', t:'auto_supervisionato', type:'isa' },
  { s:'supervisionato', t:'classificazione', type:'prereq' },
  { s:'classificazione', t:'attributi', type:'prereq' },
  { s:'classificazione', t:'albero_decisione', type:'prereq' },
  { s:'albero_decisione', t:'algoritmo_hunt', type:'prereq' },
  { s:'albero_decisione', t:'entropia', type:'prereq' },
  { s:'entropia', t:'information_gain', type:'prereq' },
  { s:'entropia', t:'gini', type:'rel' },
  { s:'information_gain', t:'gini', type:'rel' },
  { s:'albero_decisione', t:'pruning', type:'prereq' },
  { s:'pruning', t:'overfitting', type:'rel' },
  { s:'overfitting', t:'underfitting', type:'rel' },
  { s:'bias_modello', t:'underfitting', type:'prereq' },
  { s:'varianza', t:'overfitting', type:'prereq' },
  { s:'bias_modello', t:'varianza', type:'rel' },
  { s:'apprendimento', t:'rasoio_occam', type:'rel' },
  { s:'rasoio_occam', t:'mdl', type:'prereq' },
  { s:'supervisionato', t:'rote_learning_knn', type:'isa' },
  { s:'classificazione', t:'matrice_costi', type:'rel' },
  { s:'classificazione', t:'matrice_confusione', type:'prereq' },
  { s:'matrice_confusione', t:'accuratezza', type:'prereq' },
  { s:'apprendimento', t:'training_test_set', type:'prereq' },
  { s:'training_test_set', t:'cross_validation', type:'prereq' },
  { s:'non_supervisionato', t:'clustering', type:'prereq' },
  { s:'apprendimento', t:'reti_neurali', type:'rel' },
  { s:'apprendimento', t:'bias_modello', type:'rel' },

  // NN
  { s:'perceptron', t:'problema_xor', type:'prereq' },
  { s:'problema_xor', t:'reti_neurali', type:'prereq' },
  { s:'reti_neurali', t:'mlp', type:'prereq' },
  { s:'mlp', t:'backpropagation', type:'prereq' },
  { s:'backpropagation', t:'gradiente', type:'prereq' },
  { s:'reti_neurali', t:'epoca', type:'rel' },
  { s:'reti_neurali', t:'cnn', type:'isa' },
  { s:'reti_neurali', t:'rnn', type:'isa' },
  { s:'reti_neurali', t:'autoencoder', type:'isa' },
  { s:'perceptron', t:'classificazione', type:'rel' },

  // GEN
  { s:'reti_neurali', t:'ia_generativa', type:'prereq' },
  { s:'ia_generativa', t:'gan', type:'isa' },
  { s:'ia_generativa', t:'modelli_diffusione', type:'isa' },
  { s:'gan', t:'addestramento_avversariale', type:'prereq' },
  { s:'cnn', t:'modelli_diffusione', type:'rel' },
  { s:'clustering', t:'k_means', type:'prereq' },
  { s:'ia_generativa', t:'transformer', type:'rel' },

  // NLP
  { s:'language_model', t:'assunzione_markov', type:'prereq' },
  { s:'language_model', t:'naive_bayes', type:'rel' },
  { s:'naive_bayes', t:'indipendenza_condizionata', type:'prereq' },
  { s:'naive_bayes', t:'bias_dati', type:'rel' },
  { s:'language_model', t:'one_hot', type:'prereq' },
  { s:'one_hot', t:'tf_idf', type:'prereq' },
  { s:'tf_idf', t:'embeddings', type:'prereq' },
  { s:'embeddings', t:'transformer', type:'prereq' },
  { s:'language_model', t:'transformer', type:'prereq' },
  { s:'transformer', t:'attention', type:'prereq' },
  { s:'transformer', t:'encoder_decoder', type:'isa' },
  { s:'transformer', t:'masking', type:'prereq' },
  { s:'transformer', t:'residual_connections', type:'rel' },
  { s:'transformer', t:'grounding', type:'rel' },
  { s:'reti_neurali', t:'rnn', type:'rel' },

  // PR
  { s:'probabilita_var', t:'teorema_bayes', type:'prereq' },
  { s:'probabilita_var', t:'indipendenza_condizionata', type:'prereq' },
  { s:'teorema_bayes', t:'reti_bayesiane', type:'prereq' },
  { s:'indipendenza_condizionata', t:'reti_bayesiane', type:'prereq' },
  { s:'reti_bayesiane', t:'cpt', type:'prereq' },
  { s:'reti_bayesiane', t:'naive_bayes', type:'rel' },

  // PLAN
  { s:'planning', t:'pddl', type:'prereq' },
  { s:'planning', t:'situation_calculus', type:'prereq' },
  { s:'situation_calculus', t:'fluenti', type:'prereq' },
  { s:'situation_calculus', t:'assiomi_planning', type:'prereq' },
  { s:'assiomi_planning', t:'frame_problem', type:'prereq' },
  { s:'planning', t:'anomalia_sussman', type:'rel' },
  { s:'problema_ricerca', t:'planning', type:'rel' }
];

const GRAPH = { nodes: NODES, edges: EDGES, cats: CATS };

if (typeof module !== 'undefined' && module.exports) module.exports = GRAPH;
if (typeof window !== 'undefined') window.GRAPH = GRAPH;
